// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Devdraft.Client;
using Devdraft.Model;

namespace Devdraft.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IPaymentIntentsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        PaymentIntentsApiEvents Events { get; }

        /// <summary>
        /// Create a bank payment intent
        /// </summary>
        /// <remarks>
        /// Creates a new bank payment intent for fiat-to-stablecoin transfers.      This endpoint allows you to create payment intents for bank transfers (ACH, Wire, SEPA) that convert to stablecoins. Perfect for onboarding users from traditional banking to crypto.  ## Supported Payment Rails - **ACH_PUSH**: US bank transfers (same-day or standard) - **WIRE**: International wire transfers - **SEPA**: European bank transfers  ## Use Cases - USD bank account to USDC conversion - EUR bank account to EURC conversion - MXN bank account to stablecoin conversion - Flexible amount payment intents for variable pricing  ## Supported Source Currencies - **USD**: US Dollar - **EUR**: Euro - **MXN**: Mexican Peso  ## Example: USD Bank to USDC &#x60;&#x60;&#x60;json {   \&quot;sourcePaymentRail\&quot;: \&quot;ach_push\&quot;,   \&quot;sourceCurrency\&quot;: \&quot;usd\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;1000.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;ach_reference\&quot;: \&quot;INV12345\&quot; } &#x60;&#x60;&#x60;  ## Reference Fields Use appropriate reference fields based on the payment rail: - &#x60;ach_reference&#x60;: For ACH transfers (max 10 chars, alphanumeric + spaces) - &#x60;wire_message&#x60;: For wire transfers (max 256 chars) - &#x60;sepa_reference&#x60;: For SEPA transfers (6-140 chars, specific character set)  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createBankPaymentIntentDto">Bank payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateBankPaymentIntentApiResponse"/>&gt;</returns>
        Task<IPaymentIntentControllerCreateBankPaymentIntentApiResponse> PaymentIntentControllerCreateBankPaymentIntentAsync(string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a bank payment intent
        /// </summary>
        /// <remarks>
        /// Creates a new bank payment intent for fiat-to-stablecoin transfers.      This endpoint allows you to create payment intents for bank transfers (ACH, Wire, SEPA) that convert to stablecoins. Perfect for onboarding users from traditional banking to crypto.  ## Supported Payment Rails - **ACH_PUSH**: US bank transfers (same-day or standard) - **WIRE**: International wire transfers - **SEPA**: European bank transfers  ## Use Cases - USD bank account to USDC conversion - EUR bank account to EURC conversion - MXN bank account to stablecoin conversion - Flexible amount payment intents for variable pricing  ## Supported Source Currencies - **USD**: US Dollar - **EUR**: Euro - **MXN**: Mexican Peso  ## Example: USD Bank to USDC &#x60;&#x60;&#x60;json {   \&quot;sourcePaymentRail\&quot;: \&quot;ach_push\&quot;,   \&quot;sourceCurrency\&quot;: \&quot;usd\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;1000.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;ach_reference\&quot;: \&quot;INV12345\&quot; } &#x60;&#x60;&#x60;  ## Reference Fields Use appropriate reference fields based on the payment rail: - &#x60;ach_reference&#x60;: For ACH transfers (max 10 chars, alphanumeric + spaces) - &#x60;wire_message&#x60;: For wire transfers (max 256 chars) - &#x60;sepa_reference&#x60;: For SEPA transfers (6-140 chars, specific character set)  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </remarks>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createBankPaymentIntentDto">Bank payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateBankPaymentIntentApiResponse"/>&gt;</returns>
        Task<IPaymentIntentControllerCreateBankPaymentIntentApiResponse> PaymentIntentControllerCreateBankPaymentIntentOrDefaultAsync(string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a stable payment intent
        /// </summary>
        /// <remarks>
        /// Creates a new stable payment intent for stablecoin-to-stablecoin transfers.      This endpoint allows you to create payment intents for transfers between different stablecoins and networks. Perfect for cross-chain stablecoin swaps and conversions.  ## Use Cases - USDC to EURC conversions - Cross-chain stablecoin transfers (e.g., Ethereum USDC to Polygon USDC) - Flexible amount payment intents for dynamic pricing  ## Example: USDC to EURC Conversion &#x60;&#x60;&#x60;json {   \&quot;sourceCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;sourceNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;eurc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;polygon\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;100.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot; } &#x60;&#x60;&#x60;  ## Flexible Amount Payments Omit the &#x60;amount&#x60; field to create a flexible payment intent where users can specify the amount during payment.  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createStablePaymentIntentDto">Stable payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateStablePaymentIntentApiResponse"/>&gt;</returns>
        Task<IPaymentIntentControllerCreateStablePaymentIntentApiResponse> PaymentIntentControllerCreateStablePaymentIntentAsync(string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a stable payment intent
        /// </summary>
        /// <remarks>
        /// Creates a new stable payment intent for stablecoin-to-stablecoin transfers.      This endpoint allows you to create payment intents for transfers between different stablecoins and networks. Perfect for cross-chain stablecoin swaps and conversions.  ## Use Cases - USDC to EURC conversions - Cross-chain stablecoin transfers (e.g., Ethereum USDC to Polygon USDC) - Flexible amount payment intents for dynamic pricing  ## Example: USDC to EURC Conversion &#x60;&#x60;&#x60;json {   \&quot;sourceCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;sourceNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;eurc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;polygon\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;100.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot; } &#x60;&#x60;&#x60;  ## Flexible Amount Payments Omit the &#x60;amount&#x60; field to create a flexible payment intent where users can specify the amount during payment.  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </remarks>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createStablePaymentIntentDto">Stable payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateStablePaymentIntentApiResponse"/>&gt;</returns>
        Task<IPaymentIntentControllerCreateStablePaymentIntentApiResponse> PaymentIntentControllerCreateStablePaymentIntentOrDefaultAsync(string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IPaymentIntentControllerCreateBankPaymentIntentApiResponse"/>
    /// </summary>
    public interface IPaymentIntentControllerCreateBankPaymentIntentApiResponse : Devdraft.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }
    }

    /// <summary>
    /// The <see cref="IPaymentIntentControllerCreateStablePaymentIntentApiResponse"/>
    /// </summary>
    public interface IPaymentIntentControllerCreateStablePaymentIntentApiResponse : Devdraft.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class PaymentIntentsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnPaymentIntentControllerCreateBankPaymentIntent;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorPaymentIntentControllerCreateBankPaymentIntent;

        internal void ExecuteOnPaymentIntentControllerCreateBankPaymentIntent(PaymentIntentsApi.PaymentIntentControllerCreateBankPaymentIntentApiResponse apiResponse)
        {
            OnPaymentIntentControllerCreateBankPaymentIntent?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPaymentIntentControllerCreateBankPaymentIntent(Exception exception)
        {
            OnErrorPaymentIntentControllerCreateBankPaymentIntent?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnPaymentIntentControllerCreateStablePaymentIntent;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorPaymentIntentControllerCreateStablePaymentIntent;

        internal void ExecuteOnPaymentIntentControllerCreateStablePaymentIntent(PaymentIntentsApi.PaymentIntentControllerCreateStablePaymentIntentApiResponse apiResponse)
        {
            OnPaymentIntentControllerCreateStablePaymentIntent?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPaymentIntentControllerCreateStablePaymentIntent(Exception exception)
        {
            OnErrorPaymentIntentControllerCreateStablePaymentIntent?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class PaymentIntentsApi : IPaymentIntentsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<PaymentIntentsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public PaymentIntentsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentIntentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentIntentsApi(ILogger<PaymentIntentsApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, PaymentIntentsApiEvents paymentIntentsApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<PaymentIntentsApi>();
            HttpClient = httpClient;
            Events = paymentIntentsApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatPaymentIntentControllerCreateBankPaymentIntent(ref string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="idempotencyKey"></param>
        /// <param name="createBankPaymentIntentDto"></param>
        /// <returns></returns>
        private void ValidatePaymentIntentControllerCreateBankPaymentIntent(string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto)
        {
            if (idempotencyKey == null)
                throw new ArgumentNullException(nameof(idempotencyKey));

            if (createBankPaymentIntentDto == null)
                throw new ArgumentNullException(nameof(createBankPaymentIntentDto));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createBankPaymentIntentDto"></param>
        private void AfterPaymentIntentControllerCreateBankPaymentIntentDefaultImplementation(IPaymentIntentControllerCreateBankPaymentIntentApiResponse apiResponseLocalVar, string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto)
        {
            bool suppressDefaultLog = false;
            AfterPaymentIntentControllerCreateBankPaymentIntent(ref suppressDefaultLog, apiResponseLocalVar, idempotencyKey, createBankPaymentIntentDto);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createBankPaymentIntentDto"></param>
        partial void AfterPaymentIntentControllerCreateBankPaymentIntent(ref bool suppressDefaultLog, IPaymentIntentControllerCreateBankPaymentIntentApiResponse apiResponseLocalVar, string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createBankPaymentIntentDto"></param>
        private void OnErrorPaymentIntentControllerCreateBankPaymentIntentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorPaymentIntentControllerCreateBankPaymentIntent(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, idempotencyKey, createBankPaymentIntentDto);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createBankPaymentIntentDto"></param>
        partial void OnErrorPaymentIntentControllerCreateBankPaymentIntent(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto);

        /// <summary>
        /// Create a bank payment intent Creates a new bank payment intent for fiat-to-stablecoin transfers.      This endpoint allows you to create payment intents for bank transfers (ACH, Wire, SEPA) that convert to stablecoins. Perfect for onboarding users from traditional banking to crypto.  ## Supported Payment Rails - **ACH_PUSH**: US bank transfers (same-day or standard) - **WIRE**: International wire transfers - **SEPA**: European bank transfers  ## Use Cases - USD bank account to USDC conversion - EUR bank account to EURC conversion - MXN bank account to stablecoin conversion - Flexible amount payment intents for variable pricing  ## Supported Source Currencies - **USD**: US Dollar - **EUR**: Euro - **MXN**: Mexican Peso  ## Example: USD Bank to USDC &#x60;&#x60;&#x60;json {   \&quot;sourcePaymentRail\&quot;: \&quot;ach_push\&quot;,   \&quot;sourceCurrency\&quot;: \&quot;usd\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;1000.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;ach_reference\&quot;: \&quot;INV12345\&quot; } &#x60;&#x60;&#x60;  ## Reference Fields Use appropriate reference fields based on the payment rail: - &#x60;ach_reference&#x60;: For ACH transfers (max 10 chars, alphanumeric + spaces) - &#x60;wire_message&#x60;: For wire transfers (max 256 chars) - &#x60;sepa_reference&#x60;: For SEPA transfers (6-140 chars, specific character set)  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </summary>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createBankPaymentIntentDto">Bank payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateBankPaymentIntentApiResponse"/>&gt;</returns>
        public async Task<IPaymentIntentControllerCreateBankPaymentIntentApiResponse> PaymentIntentControllerCreateBankPaymentIntentOrDefaultAsync(string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PaymentIntentControllerCreateBankPaymentIntentAsync(idempotencyKey, createBankPaymentIntentDto, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create a bank payment intent Creates a new bank payment intent for fiat-to-stablecoin transfers.      This endpoint allows you to create payment intents for bank transfers (ACH, Wire, SEPA) that convert to stablecoins. Perfect for onboarding users from traditional banking to crypto.  ## Supported Payment Rails - **ACH_PUSH**: US bank transfers (same-day or standard) - **WIRE**: International wire transfers - **SEPA**: European bank transfers  ## Use Cases - USD bank account to USDC conversion - EUR bank account to EURC conversion - MXN bank account to stablecoin conversion - Flexible amount payment intents for variable pricing  ## Supported Source Currencies - **USD**: US Dollar - **EUR**: Euro - **MXN**: Mexican Peso  ## Example: USD Bank to USDC &#x60;&#x60;&#x60;json {   \&quot;sourcePaymentRail\&quot;: \&quot;ach_push\&quot;,   \&quot;sourceCurrency\&quot;: \&quot;usd\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;1000.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;ach_reference\&quot;: \&quot;INV12345\&quot; } &#x60;&#x60;&#x60;  ## Reference Fields Use appropriate reference fields based on the payment rail: - &#x60;ach_reference&#x60;: For ACH transfers (max 10 chars, alphanumeric + spaces) - &#x60;wire_message&#x60;: For wire transfers (max 256 chars) - &#x60;sepa_reference&#x60;: For SEPA transfers (6-140 chars, specific character set)  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createBankPaymentIntentDto">Bank payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateBankPaymentIntentApiResponse"/>&gt;</returns>
        public async Task<IPaymentIntentControllerCreateBankPaymentIntentApiResponse> PaymentIntentControllerCreateBankPaymentIntentAsync(string idempotencyKey, CreateBankPaymentIntentDto createBankPaymentIntentDto, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidatePaymentIntentControllerCreateBankPaymentIntent(idempotencyKey, createBankPaymentIntentDto);

                FormatPaymentIntentControllerCreateBankPaymentIntent(ref idempotencyKey, createBankPaymentIntentDto);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v0/payment-intents/bank"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v0/payment-intents/bank");

                    httpRequestMessageLocalVar.Headers.Add("idempotency-key", ClientUtils.ParameterToString(idempotencyKey));

                    httpRequestMessageLocalVar.Content = (createBankPaymentIntentDto as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createBankPaymentIntentDto, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-client-secret", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-client-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<PaymentIntentControllerCreateBankPaymentIntentApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PaymentIntentControllerCreateBankPaymentIntentApiResponse>();
                        PaymentIntentControllerCreateBankPaymentIntentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);
                                apiResponseLocalVar = new PaymentIntentControllerCreateBankPaymentIntentApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v0/payment-intents/bank", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterPaymentIntentControllerCreateBankPaymentIntentDefaultImplementation(apiResponseLocalVar, idempotencyKey, createBankPaymentIntentDto);

                        Events.ExecuteOnPaymentIntentControllerCreateBankPaymentIntent(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPaymentIntentControllerCreateBankPaymentIntentDefaultImplementation(e, "/api/v0/payment-intents/bank", uriBuilderLocalVar.Path, idempotencyKey, createBankPaymentIntentDto);
                Events.ExecuteOnErrorPaymentIntentControllerCreateBankPaymentIntent(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PaymentIntentControllerCreateBankPaymentIntentApiResponse"/>
        /// </summary>
        public partial class PaymentIntentControllerCreateBankPaymentIntentApiResponse : Devdraft.Client.ApiResponse, IPaymentIntentControllerCreateBankPaymentIntentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PaymentIntentControllerCreateBankPaymentIntentApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PaymentIntentControllerCreateBankPaymentIntentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PaymentIntentControllerCreateBankPaymentIntentApiResponse(ILogger<PaymentIntentControllerCreateBankPaymentIntentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="PaymentIntentControllerCreateBankPaymentIntentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PaymentIntentControllerCreateBankPaymentIntentApiResponse(ILogger<PaymentIntentControllerCreateBankPaymentIntentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatPaymentIntentControllerCreateStablePaymentIntent(ref string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="idempotencyKey"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        /// <returns></returns>
        private void ValidatePaymentIntentControllerCreateStablePaymentIntent(string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto)
        {
            if (idempotencyKey == null)
                throw new ArgumentNullException(nameof(idempotencyKey));

            if (createStablePaymentIntentDto == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        private void AfterPaymentIntentControllerCreateStablePaymentIntentDefaultImplementation(IPaymentIntentControllerCreateStablePaymentIntentApiResponse apiResponseLocalVar, string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto)
        {
            bool suppressDefaultLog = false;
            AfterPaymentIntentControllerCreateStablePaymentIntent(ref suppressDefaultLog, apiResponseLocalVar, idempotencyKey, createStablePaymentIntentDto);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        partial void AfterPaymentIntentControllerCreateStablePaymentIntent(ref bool suppressDefaultLog, IPaymentIntentControllerCreateStablePaymentIntentApiResponse apiResponseLocalVar, string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        private void OnErrorPaymentIntentControllerCreateStablePaymentIntentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorPaymentIntentControllerCreateStablePaymentIntent(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, idempotencyKey, createStablePaymentIntentDto);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="idempotencyKey"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        partial void OnErrorPaymentIntentControllerCreateStablePaymentIntent(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto);

        /// <summary>
        /// Create a stable payment intent Creates a new stable payment intent for stablecoin-to-stablecoin transfers.      This endpoint allows you to create payment intents for transfers between different stablecoins and networks. Perfect for cross-chain stablecoin swaps and conversions.  ## Use Cases - USDC to EURC conversions - Cross-chain stablecoin transfers (e.g., Ethereum USDC to Polygon USDC) - Flexible amount payment intents for dynamic pricing  ## Example: USDC to EURC Conversion &#x60;&#x60;&#x60;json {   \&quot;sourceCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;sourceNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;eurc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;polygon\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;100.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot; } &#x60;&#x60;&#x60;  ## Flexible Amount Payments Omit the &#x60;amount&#x60; field to create a flexible payment intent where users can specify the amount during payment.  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </summary>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createStablePaymentIntentDto">Stable payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateStablePaymentIntentApiResponse"/>&gt;</returns>
        public async Task<IPaymentIntentControllerCreateStablePaymentIntentApiResponse> PaymentIntentControllerCreateStablePaymentIntentOrDefaultAsync(string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PaymentIntentControllerCreateStablePaymentIntentAsync(idempotencyKey, createStablePaymentIntentDto, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create a stable payment intent Creates a new stable payment intent for stablecoin-to-stablecoin transfers.      This endpoint allows you to create payment intents for transfers between different stablecoins and networks. Perfect for cross-chain stablecoin swaps and conversions.  ## Use Cases - USDC to EURC conversions - Cross-chain stablecoin transfers (e.g., Ethereum USDC to Polygon USDC) - Flexible amount payment intents for dynamic pricing  ## Example: USDC to EURC Conversion &#x60;&#x60;&#x60;json {   \&quot;sourceCurrency\&quot;: \&quot;usdc\&quot;,   \&quot;sourceNetwork\&quot;: \&quot;ethereum\&quot;,   \&quot;destinationCurrency\&quot;: \&quot;eurc\&quot;,   \&quot;destinationNetwork\&quot;: \&quot;polygon\&quot;,   \&quot;destinationAddress\&quot;: \&quot;0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1\&quot;,   \&quot;amount\&quot;: \&quot;100.00\&quot;,   \&quot;customer_first_name\&quot;: \&quot;John\&quot;,   \&quot;customer_last_name\&quot;: \&quot;Doe\&quot;,   \&quot;customer_email\&quot;: \&quot;john.doe@example.com\&quot; } &#x60;&#x60;&#x60;  ## Flexible Amount Payments Omit the &#x60;amount&#x60; field to create a flexible payment intent where users can specify the amount during payment.  ## Idempotency Include an &#x60;idempotency-key&#x60; header with a unique UUID v4 to prevent duplicate payments. Subsequent requests with the same key will return the original response.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="idempotencyKey">Unique UUID v4 for idempotent requests. Prevents duplicate payments.</param>
        /// <param name="createStablePaymentIntentDto">Stable payment intent creation data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPaymentIntentControllerCreateStablePaymentIntentApiResponse"/>&gt;</returns>
        public async Task<IPaymentIntentControllerCreateStablePaymentIntentApiResponse> PaymentIntentControllerCreateStablePaymentIntentAsync(string idempotencyKey, CreateStablePaymentIntentDto createStablePaymentIntentDto, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidatePaymentIntentControllerCreateStablePaymentIntent(idempotencyKey, createStablePaymentIntentDto);

                FormatPaymentIntentControllerCreateStablePaymentIntent(ref idempotencyKey, createStablePaymentIntentDto);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v0/payment-intents/stablecoin"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v0/payment-intents/stablecoin");

                    httpRequestMessageLocalVar.Headers.Add("idempotency-key", ClientUtils.ParameterToString(idempotencyKey));

                    httpRequestMessageLocalVar.Content = (createStablePaymentIntentDto as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createStablePaymentIntentDto, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-client-secret", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-client-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<PaymentIntentControllerCreateStablePaymentIntentApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PaymentIntentControllerCreateStablePaymentIntentApiResponse>();
                        PaymentIntentControllerCreateStablePaymentIntentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);
                                apiResponseLocalVar = new PaymentIntentControllerCreateStablePaymentIntentApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v0/payment-intents/stablecoin", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterPaymentIntentControllerCreateStablePaymentIntentDefaultImplementation(apiResponseLocalVar, idempotencyKey, createStablePaymentIntentDto);

                        Events.ExecuteOnPaymentIntentControllerCreateStablePaymentIntent(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPaymentIntentControllerCreateStablePaymentIntentDefaultImplementation(e, "/api/v0/payment-intents/stablecoin", uriBuilderLocalVar.Path, idempotencyKey, createStablePaymentIntentDto);
                Events.ExecuteOnErrorPaymentIntentControllerCreateStablePaymentIntent(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PaymentIntentControllerCreateStablePaymentIntentApiResponse"/>
        /// </summary>
        public partial class PaymentIntentControllerCreateStablePaymentIntentApiResponse : Devdraft.Client.ApiResponse, IPaymentIntentControllerCreateStablePaymentIntentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PaymentIntentControllerCreateStablePaymentIntentApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PaymentIntentControllerCreateStablePaymentIntentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PaymentIntentControllerCreateStablePaymentIntentApiResponse(ILogger<PaymentIntentControllerCreateStablePaymentIntentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="PaymentIntentControllerCreateStablePaymentIntentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PaymentIntentControllerCreateStablePaymentIntentApiResponse(ILogger<PaymentIntentControllerCreateStablePaymentIntentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
