/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing AggregatedBalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregatedBalanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggregatedBalanceResponse
        //private AggregatedBalanceResponse instance;

        public AggregatedBalanceResponseTests()
        {
            // TODO uncomment below to create an instance of AggregatedBalanceResponse
            //instance = new AggregatedBalanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregatedBalanceResponse
        /// </summary>
        [Fact]
        public void AggregatedBalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggregatedBalanceResponse
            //Assert.IsType<AggregatedBalanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'TotalBalance'
        /// </summary>
        [Fact]
        public void TotalBalanceTest()
        {
            // TODO unit test for the property 'TotalBalance'
        }

        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Fact]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }
    }
}
