/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing AllBalancesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllBalancesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AllBalancesResponse
        //private AllBalancesResponse instance;

        public AllBalancesResponseTests()
        {
            // TODO uncomment below to create an instance of AllBalancesResponse
            //instance = new AllBalancesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AllBalancesResponse
        /// </summary>
        [Fact]
        public void AllBalancesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AllBalancesResponse
            //Assert.IsType<AllBalancesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Usdc'
        /// </summary>
        [Fact]
        public void UsdcTest()
        {
            // TODO unit test for the property 'Usdc'
        }

        /// <summary>
        /// Test the property 'Eurc'
        /// </summary>
        [Fact]
        public void EurcTest()
        {
            // TODO unit test for the property 'Eurc'
        }

        /// <summary>
        /// Test the property 'TotalUsdValue'
        /// </summary>
        [Fact]
        public void TotalUsdValueTest()
        {
            // TODO unit test for the property 'TotalUsdValue'
        }
    }
}
