/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing CreateDirectBankTransferDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateDirectBankTransferDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateDirectBankTransferDto
        //private CreateDirectBankTransferDto instance;

        public CreateDirectBankTransferDtoTests()
        {
            // TODO uncomment below to create an instance of CreateDirectBankTransferDto
            //instance = new CreateDirectBankTransferDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateDirectBankTransferDto
        /// </summary>
        [Fact]
        public void CreateDirectBankTransferDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateDirectBankTransferDto
            //Assert.IsType<CreateDirectBankTransferDto>(instance);
        }

        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Fact]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }

        /// <summary>
        /// Test the property 'PaymentRail'
        /// </summary>
        [Fact]
        public void PaymentRailTest()
        {
            // TODO unit test for the property 'PaymentRail'
        }

        /// <summary>
        /// Test the property 'DestinationCurrency'
        /// </summary>
        [Fact]
        public void DestinationCurrencyTest()
        {
            // TODO unit test for the property 'DestinationCurrency'
        }

        /// <summary>
        /// Test the property 'SourceCurrency'
        /// </summary>
        [Fact]
        public void SourceCurrencyTest()
        {
            // TODO unit test for the property 'SourceCurrency'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'WireMessage'
        /// </summary>
        [Fact]
        public void WireMessageTest()
        {
            // TODO unit test for the property 'WireMessage'
        }

        /// <summary>
        /// Test the property 'SepaReference'
        /// </summary>
        [Fact]
        public void SepaReferenceTest()
        {
            // TODO unit test for the property 'SepaReference'
        }

        /// <summary>
        /// Test the property 'AchReference'
        /// </summary>
        [Fact]
        public void AchReferenceTest()
        {
            // TODO unit test for the property 'AchReference'
        }
    }
}
