/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing CreateExternalBankTransferDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateExternalBankTransferDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateExternalBankTransferDto
        //private CreateExternalBankTransferDto instance;

        public CreateExternalBankTransferDtoTests()
        {
            // TODO uncomment below to create an instance of CreateExternalBankTransferDto
            //instance = new CreateExternalBankTransferDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateExternalBankTransferDto
        /// </summary>
        [Fact]
        public void CreateExternalBankTransferDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateExternalBankTransferDto
            //Assert.IsType<CreateExternalBankTransferDto>(instance);
        }

        /// <summary>
        /// Test the property 'SourceWalletId'
        /// </summary>
        [Fact]
        public void SourceWalletIdTest()
        {
            // TODO unit test for the property 'SourceWalletId'
        }

        /// <summary>
        /// Test the property 'SourceCurrency'
        /// </summary>
        [Fact]
        public void SourceCurrencyTest()
        {
            // TODO unit test for the property 'SourceCurrency'
        }

        /// <summary>
        /// Test the property 'DestinationCurrency'
        /// </summary>
        [Fact]
        public void DestinationCurrencyTest()
        {
            // TODO unit test for the property 'DestinationCurrency'
        }

        /// <summary>
        /// Test the property 'DestinationPaymentRail'
        /// </summary>
        [Fact]
        public void DestinationPaymentRailTest()
        {
            // TODO unit test for the property 'DestinationPaymentRail'
        }

        /// <summary>
        /// Test the property 'ExternalAccountId'
        /// </summary>
        [Fact]
        public void ExternalAccountIdTest()
        {
            // TODO unit test for the property 'ExternalAccountId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'WireMessage'
        /// </summary>
        [Fact]
        public void WireMessageTest()
        {
            // TODO unit test for the property 'WireMessage'
        }

        /// <summary>
        /// Test the property 'SepaReference'
        /// </summary>
        [Fact]
        public void SepaReferenceTest()
        {
            // TODO unit test for the property 'SepaReference'
        }

        /// <summary>
        /// Test the property 'SwiftReference'
        /// </summary>
        [Fact]
        public void SwiftReferenceTest()
        {
            // TODO unit test for the property 'SwiftReference'
        }

        /// <summary>
        /// Test the property 'SpeiReference'
        /// </summary>
        [Fact]
        public void SpeiReferenceTest()
        {
            // TODO unit test for the property 'SpeiReference'
        }

        /// <summary>
        /// Test the property 'SwiftCharges'
        /// </summary>
        [Fact]
        public void SwiftChargesTest()
        {
            // TODO unit test for the property 'SwiftCharges'
        }

        /// <summary>
        /// Test the property 'AchReference'
        /// </summary>
        [Fact]
        public void AchReferenceTest()
        {
            // TODO unit test for the property 'AchReference'
        }
    }
}
