/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerType
        //private CustomerType instance;

        public CustomerTypeTests()
        {
            // TODO uncomment below to create an instance of CustomerType
            //instance = new CustomerType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerType
        /// </summary>
        [Fact]
        public void CustomerTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerType
            //Assert.IsType<CustomerType>(instance);
        }
    }
}
