/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing HealthResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthResponseDto
        //private HealthResponseDto instance;

        public HealthResponseDtoTests()
        {
            // TODO uncomment below to create an instance of HealthResponseDto
            //instance = new HealthResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthResponseDto
        /// </summary>
        [Fact]
        public void HealthResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthResponseDto
            //Assert.IsType<HealthResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Fact]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Authenticated'
        /// </summary>
        [Fact]
        public void AuthenticatedTest()
        {
            // TODO unit test for the property 'Authenticated'
        }
    }
}
