/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing TaxControllerUpdateWithoutId400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxControllerUpdateWithoutId400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaxControllerUpdateWithoutId400Response
        //private TaxControllerUpdateWithoutId400Response instance;

        public TaxControllerUpdateWithoutId400ResponseTests()
        {
            // TODO uncomment below to create an instance of TaxControllerUpdateWithoutId400Response
            //instance = new TaxControllerUpdateWithoutId400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaxControllerUpdateWithoutId400Response
        /// </summary>
        [Fact]
        public void TaxControllerUpdateWithoutId400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaxControllerUpdateWithoutId400Response
            //Assert.IsType<TaxControllerUpdateWithoutId400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
