/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Devdraft.Model;
using Devdraft.Client;
using System.Reflection;

namespace Devdraft.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCustomerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCustomerDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCustomerDto
        //private UpdateCustomerDto instance;

        public UpdateCustomerDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateCustomerDto
            //instance = new UpdateCustomerDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCustomerDto
        /// </summary>
        [Fact]
        public void UpdateCustomerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCustomerDto
            //Assert.IsType<UpdateCustomerDto>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'CustomerType'
        /// </summary>
        [Fact]
        public void CustomerTypeTest()
        {
            // TODO unit test for the property 'CustomerType'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
