// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// The blockchain network where the source currency resides. Determines gas fees and transaction speed.
    /// </summary>
    /// <value>The blockchain network where the source currency resides. Determines gas fees and transaction speed.</value>
    public enum BridgePaymentRail
    {
        /// <summary>
        /// Enum Ethereum for value: ethereum
        /// </summary>
        Ethereum = 1,

        /// <summary>
        /// Enum Solana for value: solana
        /// </summary>
        Solana = 2,

        /// <summary>
        /// Enum Polygon for value: polygon
        /// </summary>
        Polygon = 3,

        /// <summary>
        /// Enum AvalancheCChain for value: avalanche_c_chain
        /// </summary>
        AvalancheCChain = 4,

        /// <summary>
        /// Enum Base for value: base
        /// </summary>
        Base = 5,

        /// <summary>
        /// Enum Arbitrum for value: arbitrum
        /// </summary>
        Arbitrum = 6,

        /// <summary>
        /// Enum Optimism for value: optimism
        /// </summary>
        Optimism = 7,

        /// <summary>
        /// Enum Stellar for value: stellar
        /// </summary>
        Stellar = 8,

        /// <summary>
        /// Enum Tron for value: tron
        /// </summary>
        Tron = 9,

        /// <summary>
        /// Enum BridgeWallet for value: bridge_wallet
        /// </summary>
        BridgeWallet = 10,

        /// <summary>
        /// Enum Wire for value: wire
        /// </summary>
        Wire = 11,

        /// <summary>
        /// Enum Ach for value: ach
        /// </summary>
        Ach = 12,

        /// <summary>
        /// Enum AchPush for value: ach_push
        /// </summary>
        AchPush = 13,

        /// <summary>
        /// Enum AchSameDay for value: ach_same_day
        /// </summary>
        AchSameDay = 14,

        /// <summary>
        /// Enum Sepa for value: sepa
        /// </summary>
        Sepa = 15,

        /// <summary>
        /// Enum Swift for value: swift
        /// </summary>
        Swift = 16,

        /// <summary>
        /// Enum Spei for value: spei
        /// </summary>
        Spei = 17
    }

    /// <summary>
    /// Converts <see cref="BridgePaymentRail"/> to and from the JSON value
    /// </summary>
    public static class BridgePaymentRailValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BridgePaymentRail"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BridgePaymentRail FromString(string value)
        {
            if (value.Equals("ethereum"))
                return BridgePaymentRail.Ethereum;

            if (value.Equals("solana"))
                return BridgePaymentRail.Solana;

            if (value.Equals("polygon"))
                return BridgePaymentRail.Polygon;

            if (value.Equals("avalanche_c_chain"))
                return BridgePaymentRail.AvalancheCChain;

            if (value.Equals("base"))
                return BridgePaymentRail.Base;

            if (value.Equals("arbitrum"))
                return BridgePaymentRail.Arbitrum;

            if (value.Equals("optimism"))
                return BridgePaymentRail.Optimism;

            if (value.Equals("stellar"))
                return BridgePaymentRail.Stellar;

            if (value.Equals("tron"))
                return BridgePaymentRail.Tron;

            if (value.Equals("bridge_wallet"))
                return BridgePaymentRail.BridgeWallet;

            if (value.Equals("wire"))
                return BridgePaymentRail.Wire;

            if (value.Equals("ach"))
                return BridgePaymentRail.Ach;

            if (value.Equals("ach_push"))
                return BridgePaymentRail.AchPush;

            if (value.Equals("ach_same_day"))
                return BridgePaymentRail.AchSameDay;

            if (value.Equals("sepa"))
                return BridgePaymentRail.Sepa;

            if (value.Equals("swift"))
                return BridgePaymentRail.Swift;

            if (value.Equals("spei"))
                return BridgePaymentRail.Spei;

            throw new NotImplementedException($"Could not convert value to type BridgePaymentRail: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BridgePaymentRail"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BridgePaymentRail? FromStringOrDefault(string value)
        {
            if (value.Equals("ethereum"))
                return BridgePaymentRail.Ethereum;

            if (value.Equals("solana"))
                return BridgePaymentRail.Solana;

            if (value.Equals("polygon"))
                return BridgePaymentRail.Polygon;

            if (value.Equals("avalanche_c_chain"))
                return BridgePaymentRail.AvalancheCChain;

            if (value.Equals("base"))
                return BridgePaymentRail.Base;

            if (value.Equals("arbitrum"))
                return BridgePaymentRail.Arbitrum;

            if (value.Equals("optimism"))
                return BridgePaymentRail.Optimism;

            if (value.Equals("stellar"))
                return BridgePaymentRail.Stellar;

            if (value.Equals("tron"))
                return BridgePaymentRail.Tron;

            if (value.Equals("bridge_wallet"))
                return BridgePaymentRail.BridgeWallet;

            if (value.Equals("wire"))
                return BridgePaymentRail.Wire;

            if (value.Equals("ach"))
                return BridgePaymentRail.Ach;

            if (value.Equals("ach_push"))
                return BridgePaymentRail.AchPush;

            if (value.Equals("ach_same_day"))
                return BridgePaymentRail.AchSameDay;

            if (value.Equals("sepa"))
                return BridgePaymentRail.Sepa;

            if (value.Equals("swift"))
                return BridgePaymentRail.Swift;

            if (value.Equals("spei"))
                return BridgePaymentRail.Spei;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BridgePaymentRail"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BridgePaymentRail value)
        {
            if (value == BridgePaymentRail.Ethereum)
                return "ethereum";

            if (value == BridgePaymentRail.Solana)
                return "solana";

            if (value == BridgePaymentRail.Polygon)
                return "polygon";

            if (value == BridgePaymentRail.AvalancheCChain)
                return "avalanche_c_chain";

            if (value == BridgePaymentRail.Base)
                return "base";

            if (value == BridgePaymentRail.Arbitrum)
                return "arbitrum";

            if (value == BridgePaymentRail.Optimism)
                return "optimism";

            if (value == BridgePaymentRail.Stellar)
                return "stellar";

            if (value == BridgePaymentRail.Tron)
                return "tron";

            if (value == BridgePaymentRail.BridgeWallet)
                return "bridge_wallet";

            if (value == BridgePaymentRail.Wire)
                return "wire";

            if (value == BridgePaymentRail.Ach)
                return "ach";

            if (value == BridgePaymentRail.AchPush)
                return "ach_push";

            if (value == BridgePaymentRail.AchSameDay)
                return "ach_same_day";

            if (value == BridgePaymentRail.Sepa)
                return "sepa";

            if (value == BridgePaymentRail.Swift)
                return "swift";

            if (value == BridgePaymentRail.Spei)
                return "spei";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BridgePaymentRail"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BridgePaymentRailJsonConverter : JsonConverter<BridgePaymentRail>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BridgePaymentRail Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BridgePaymentRail? result = rawValue == null
                ? null
                : BridgePaymentRailValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BridgePaymentRail to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bridgePaymentRail"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BridgePaymentRail bridgePaymentRail, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BridgePaymentRailValueConverter.ToJsonValue(bridgePaymentRail).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BridgePaymentRail"/>
    /// </summary>
    public class BridgePaymentRailNullableJsonConverter : JsonConverter<BridgePaymentRail?>
    {
        /// <summary>
        /// Returns a BridgePaymentRail from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BridgePaymentRail? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BridgePaymentRail? result = rawValue == null
                ? null
                : BridgePaymentRailValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BridgePaymentRail to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bridgePaymentRail"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BridgePaymentRail? bridgePaymentRail, JsonSerializerOptions options)
        {
            writer.WriteStringValue(bridgePaymentRail.HasValue ? BridgePaymentRailValueConverter.ToJsonValue(bridgePaymentRail.Value).ToString() : "null");
        }
    }
}
