// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// CreateDirectBankTransferDto
    /// </summary>
    public partial class CreateDirectBankTransferDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDirectBankTransferDto" /> class.
        /// </summary>
        /// <param name="walletId">The ID of the bridge wallet to transfer from</param>
        /// <param name="paymentRail">The payment rail to use</param>
        /// <param name="destinationCurrency">The destination currency</param>
        /// <param name="sourceCurrency">The source currency</param>
        /// <param name="amount">The amount to transfer</param>
        /// <param name="wireMessage">Wire transfer message</param>
        /// <param name="sepaReference">SEPA transfer reference</param>
        /// <param name="achReference">ACH transfer reference</param>
        [JsonConstructor]
        public CreateDirectBankTransferDto(string walletId, string paymentRail, string destinationCurrency, string sourceCurrency, decimal amount, Option<string> wireMessage = default, Option<string> sepaReference = default, Option<string> achReference = default)
        {
            WalletId = walletId;
            PaymentRail = paymentRail;
            DestinationCurrency = destinationCurrency;
            SourceCurrency = sourceCurrency;
            Amount = amount;
            WireMessageOption = wireMessage;
            SepaReferenceOption = sepaReference;
            AchReferenceOption = achReference;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The ID of the bridge wallet to transfer from
        /// </summary>
        /// <value>The ID of the bridge wallet to transfer from</value>
        [JsonPropertyName("walletId")]
        public string WalletId { get; set; }

        /// <summary>
        /// The payment rail to use
        /// </summary>
        /// <value>The payment rail to use</value>
        [JsonPropertyName("paymentRail")]
        public string PaymentRail { get; set; }

        /// <summary>
        /// The destination currency
        /// </summary>
        /// <value>The destination currency</value>
        [JsonPropertyName("destinationCurrency")]
        public string DestinationCurrency { get; set; }

        /// <summary>
        /// The source currency
        /// </summary>
        /// <value>The source currency</value>
        [JsonPropertyName("sourceCurrency")]
        public string SourceCurrency { get; set; }

        /// <summary>
        /// The amount to transfer
        /// </summary>
        /// <value>The amount to transfer</value>
        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Used to track the state of WireMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> WireMessageOption { get; private set; }

        /// <summary>
        /// Wire transfer message
        /// </summary>
        /// <value>Wire transfer message</value>
        [JsonPropertyName("wire_message")]
        public string WireMessage { get { return this.WireMessageOption; } set { this.WireMessageOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of SepaReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> SepaReferenceOption { get; private set; }

        /// <summary>
        /// SEPA transfer reference
        /// </summary>
        /// <value>SEPA transfer reference</value>
        [JsonPropertyName("sepa_reference")]
        public string SepaReference { get { return this.SepaReferenceOption; } set { this.SepaReferenceOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of AchReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AchReferenceOption { get; private set; }

        /// <summary>
        /// ACH transfer reference
        /// </summary>
        /// <value>ACH transfer reference</value>
        [JsonPropertyName("ach_reference")]
        public string AchReference { get { return this.AchReferenceOption; } set { this.AchReferenceOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDirectBankTransferDto {\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  PaymentRail: ").Append(PaymentRail).Append("\n");
            sb.Append("  DestinationCurrency: ").Append(DestinationCurrency).Append("\n");
            sb.Append("  SourceCurrency: ").Append(SourceCurrency).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  WireMessage: ").Append(WireMessage).Append("\n");
            sb.Append("  SepaReference: ").Append(SepaReference).Append("\n");
            sb.Append("  AchReference: ").Append(AchReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateDirectBankTransferDto" />
    /// </summary>
    public class CreateDirectBankTransferDtoJsonConverter : JsonConverter<CreateDirectBankTransferDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateDirectBankTransferDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateDirectBankTransferDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> walletId = default;
            Option<string> paymentRail = default;
            Option<string> destinationCurrency = default;
            Option<string> sourceCurrency = default;
            Option<decimal?> amount = default;
            Option<string> wireMessage = default;
            Option<string> sepaReference = default;
            Option<string> achReference = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletId":
                            walletId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "paymentRail":
                            paymentRail = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destinationCurrency":
                            destinationCurrency = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "sourceCurrency":
                            sourceCurrency = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "wire_message":
                            wireMessage = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "sepa_reference":
                            sepaReference = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "ach_reference":
                            achReference = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!walletId.IsSet)
                throw new ArgumentException("Property is required for class CreateDirectBankTransferDto.", nameof(walletId));

            if (!paymentRail.IsSet)
                throw new ArgumentException("Property is required for class CreateDirectBankTransferDto.", nameof(paymentRail));

            if (!destinationCurrency.IsSet)
                throw new ArgumentException("Property is required for class CreateDirectBankTransferDto.", nameof(destinationCurrency));

            if (!sourceCurrency.IsSet)
                throw new ArgumentException("Property is required for class CreateDirectBankTransferDto.", nameof(sourceCurrency));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class CreateDirectBankTransferDto.", nameof(amount));

            if (walletId.IsSet && walletId.Value == null)
                throw new ArgumentNullException(nameof(walletId), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (paymentRail.IsSet && paymentRail.Value == null)
                throw new ArgumentNullException(nameof(paymentRail), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (destinationCurrency.IsSet && destinationCurrency.Value == null)
                throw new ArgumentNullException(nameof(destinationCurrency), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (sourceCurrency.IsSet && sourceCurrency.Value == null)
                throw new ArgumentNullException(nameof(sourceCurrency), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (wireMessage.IsSet && wireMessage.Value == null)
                throw new ArgumentNullException(nameof(wireMessage), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (sepaReference.IsSet && sepaReference.Value == null)
                throw new ArgumentNullException(nameof(sepaReference), "Property is not nullable for class CreateDirectBankTransferDto.");

            if (achReference.IsSet && achReference.Value == null)
                throw new ArgumentNullException(nameof(achReference), "Property is not nullable for class CreateDirectBankTransferDto.");

            return new CreateDirectBankTransferDto(walletId.Value, paymentRail.Value, destinationCurrency.Value, sourceCurrency.Value, amount.Value.Value, wireMessage, sepaReference, achReference);
        }

        /// <summary>
        /// Serializes a <see cref="CreateDirectBankTransferDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDirectBankTransferDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateDirectBankTransferDto createDirectBankTransferDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createDirectBankTransferDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateDirectBankTransferDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDirectBankTransferDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateDirectBankTransferDto createDirectBankTransferDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createDirectBankTransferDto.WalletId == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.WalletId), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.PaymentRail == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.PaymentRail), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.DestinationCurrency == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.DestinationCurrency), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.SourceCurrency == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.SourceCurrency), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.WireMessageOption.IsSet && createDirectBankTransferDto.WireMessage == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.WireMessage), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.SepaReferenceOption.IsSet && createDirectBankTransferDto.SepaReference == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.SepaReference), "Property is required for class CreateDirectBankTransferDto.");

            if (createDirectBankTransferDto.AchReferenceOption.IsSet && createDirectBankTransferDto.AchReference == null)
                throw new ArgumentNullException(nameof(createDirectBankTransferDto.AchReference), "Property is required for class CreateDirectBankTransferDto.");

            writer.WriteString("walletId", createDirectBankTransferDto.WalletId);

            writer.WriteString("paymentRail", createDirectBankTransferDto.PaymentRail);

            writer.WriteString("destinationCurrency", createDirectBankTransferDto.DestinationCurrency);

            writer.WriteString("sourceCurrency", createDirectBankTransferDto.SourceCurrency);

            writer.WriteNumber("amount", createDirectBankTransferDto.Amount);

            if (createDirectBankTransferDto.WireMessageOption.IsSet)
                writer.WriteString("wire_message", createDirectBankTransferDto.WireMessage);

            if (createDirectBankTransferDto.SepaReferenceOption.IsSet)
                writer.WriteString("sepa_reference", createDirectBankTransferDto.SepaReference);

            if (createDirectBankTransferDto.AchReferenceOption.IsSet)
                writer.WriteString("ach_reference", createDirectBankTransferDto.AchReference);
        }
    }
}
