// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// CreateStablePaymentIntentDto
    /// </summary>
    public partial class CreateStablePaymentIntentDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStablePaymentIntentDto" /> class.
        /// </summary>
        /// <param name="sourceCurrency">The stablecoin currency to convert FROM. This is the currency the customer will pay with.</param>
        /// <param name="sourceNetwork">The blockchain network where the source currency resides. Determines gas fees and transaction speed.</param>
        /// <param name="destinationNetwork">The blockchain network where the converted currency will be delivered. Must support the destination currency.</param>
        /// <param name="destinationCurrency">The stablecoin currency to convert TO. If omitted, defaults to the same as source currency (cross-chain transfer).</param>
        /// <param name="destinationAddress">The wallet address where converted funds will be sent. Supports Ethereum (0x...) and Solana address formats.</param>
        /// <param name="amount">Payment amount in the source currency. Omit for flexible amount payments where users specify the amount during checkout.</param>
        /// <param name="customerFirstName">Customer&#39;s first name. Used for transaction records and compliance. Required for amounts over $1000.</param>
        /// <param name="customerLastName">Customer&#39;s last name. Used for transaction records and compliance. Required for amounts over $1000.</param>
        /// <param name="customerEmail">Customer&#39;s email address. Used for transaction notifications and receipts. Highly recommended for all transactions.</param>
        /// <param name="customerAddress">Customer&#39;s full address. Required for compliance in certain jurisdictions and high-value transactions.</param>
        /// <param name="customerCountry">Customer&#39;s country of residence. Used for compliance and tax reporting.</param>
        /// <param name="customerCountryISO">Customer&#39;s country ISO 3166-1 alpha-2 code. Used for automated compliance checks.</param>
        /// <param name="customerProvince">Customer&#39;s state or province. Required for US and Canadian customers.</param>
        /// <param name="customerProvinceISO">Customer&#39;s state or province ISO code. Used for automated tax calculations.</param>
        /// <param name="phoneNumber">Customer&#39;s phone number with country code. Used for SMS notifications and verification.</param>
        [JsonConstructor]
        public CreateStablePaymentIntentDto(StableCoinCurrency sourceCurrency, BridgePaymentRail sourceNetwork, BridgePaymentRail destinationNetwork, Option<StableCoinCurrency?> destinationCurrency = default, Option<string> destinationAddress = default, Option<string> amount = default, Option<string> customerFirstName = default, Option<string> customerLastName = default, Option<string> customerEmail = default, Option<string> customerAddress = default, Option<string> customerCountry = default, Option<string> customerCountryISO = default, Option<string> customerProvince = default, Option<string> customerProvinceISO = default, Option<string> phoneNumber = default)
        {
            SourceCurrency = sourceCurrency;
            SourceNetwork = sourceNetwork;
            DestinationNetwork = destinationNetwork;
            DestinationCurrencyOption = destinationCurrency;
            DestinationAddressOption = destinationAddress;
            AmountOption = amount;
            CustomerFirstNameOption = customerFirstName;
            CustomerLastNameOption = customerLastName;
            CustomerEmailOption = customerEmail;
            CustomerAddressOption = customerAddress;
            CustomerCountryOption = customerCountry;
            CustomerCountryISOOption = customerCountryISO;
            CustomerProvinceOption = customerProvince;
            CustomerProvinceISOOption = customerProvinceISO;
            PhoneNumberOption = phoneNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The stablecoin currency to convert FROM. This is the currency the customer will pay with.
        /// </summary>
        /// <value>The stablecoin currency to convert FROM. This is the currency the customer will pay with.</value>
        [JsonPropertyName("sourceCurrency")]
        public StableCoinCurrency SourceCurrency { get; set; }

        /// <summary>
        /// The blockchain network where the source currency resides. Determines gas fees and transaction speed.
        /// </summary>
        /// <value>The blockchain network where the source currency resides. Determines gas fees and transaction speed.</value>
        [JsonPropertyName("sourceNetwork")]
        public BridgePaymentRail SourceNetwork { get; set; }

        /// <summary>
        /// The blockchain network where the converted currency will be delivered. Must support the destination currency.
        /// </summary>
        /// <value>The blockchain network where the converted currency will be delivered. Must support the destination currency.</value>
        [JsonPropertyName("destinationNetwork")]
        public BridgePaymentRail DestinationNetwork { get; set; }

        /// <summary>
        /// Used to track the state of DestinationCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StableCoinCurrency?> DestinationCurrencyOption { get; private set; }

        /// <summary>
        /// The stablecoin currency to convert TO. If omitted, defaults to the same as source currency (cross-chain transfer).
        /// </summary>
        /// <value>The stablecoin currency to convert TO. If omitted, defaults to the same as source currency (cross-chain transfer).</value>
        [JsonPropertyName("destinationCurrency")]
        public StableCoinCurrency? DestinationCurrency { get { return this.DestinationCurrencyOption; } set { this.DestinationCurrencyOption = new Option<StableCoinCurrency?>(value); } }

        /// <summary>
        /// Used to track the state of DestinationAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationAddressOption { get; private set; }

        /// <summary>
        /// The wallet address where converted funds will be sent. Supports Ethereum (0x...) and Solana address formats.
        /// </summary>
        /// <value>The wallet address where converted funds will be sent. Supports Ethereum (0x...) and Solana address formats.</value>
        /* <example>0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8e1</example> */
        [JsonPropertyName("destinationAddress")]
        public string DestinationAddress { get { return this.DestinationAddressOption; } set { this.DestinationAddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AmountOption { get; private set; }

        /// <summary>
        /// Payment amount in the source currency. Omit for flexible amount payments where users specify the amount during checkout.
        /// </summary>
        /// <value>Payment amount in the source currency. Omit for flexible amount payments where users specify the amount during checkout.</value>
        /* <example>100.50</example> */
        [JsonPropertyName("amount")]
        public string Amount { get { return this.AmountOption; } set { this.AmountOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerFirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerFirstNameOption { get; private set; }

        /// <summary>
        /// Customer&#39;s first name. Used for transaction records and compliance. Required for amounts over $1000.
        /// </summary>
        /// <value>Customer&#39;s first name. Used for transaction records and compliance. Required for amounts over $1000.</value>
        /* <example>John</example> */
        [JsonPropertyName("customer_first_name")]
        public string CustomerFirstName { get { return this.CustomerFirstNameOption; } set { this.CustomerFirstNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerLastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerLastNameOption { get; private set; }

        /// <summary>
        /// Customer&#39;s last name. Used for transaction records and compliance. Required for amounts over $1000.
        /// </summary>
        /// <value>Customer&#39;s last name. Used for transaction records and compliance. Required for amounts over $1000.</value>
        /* <example>Doe</example> */
        [JsonPropertyName("customer_last_name")]
        public string CustomerLastName { get { return this.CustomerLastNameOption; } set { this.CustomerLastNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerEmailOption { get; private set; }

        /// <summary>
        /// Customer&#39;s email address. Used for transaction notifications and receipts. Highly recommended for all transactions.
        /// </summary>
        /// <value>Customer&#39;s email address. Used for transaction notifications and receipts. Highly recommended for all transactions.</value>
        /* <example>john.doe@example.com</example> */
        [JsonPropertyName("customer_email")]
        public string CustomerEmail { get { return this.CustomerEmailOption; } set { this.CustomerEmailOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerAddressOption { get; private set; }

        /// <summary>
        /// Customer&#39;s full address. Required for compliance in certain jurisdictions and high-value transactions.
        /// </summary>
        /// <value>Customer&#39;s full address. Required for compliance in certain jurisdictions and high-value transactions.</value>
        /* <example>123 Main St, New York, NY 10001</example> */
        [JsonPropertyName("customer_address")]
        public string CustomerAddress { get { return this.CustomerAddressOption; } set { this.CustomerAddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerCountry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerCountryOption { get; private set; }

        /// <summary>
        /// Customer&#39;s country of residence. Used for compliance and tax reporting.
        /// </summary>
        /// <value>Customer&#39;s country of residence. Used for compliance and tax reporting.</value>
        /* <example>United States</example> */
        [JsonPropertyName("customer_country")]
        public string CustomerCountry { get { return this.CustomerCountryOption; } set { this.CustomerCountryOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerCountryISO
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerCountryISOOption { get; private set; }

        /// <summary>
        /// Customer&#39;s country ISO 3166-1 alpha-2 code. Used for automated compliance checks.
        /// </summary>
        /// <value>Customer&#39;s country ISO 3166-1 alpha-2 code. Used for automated compliance checks.</value>
        /* <example>US</example> */
        [JsonPropertyName("customer_countryISO")]
        public string CustomerCountryISO { get { return this.CustomerCountryISOOption; } set { this.CustomerCountryISOOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerProvince
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerProvinceOption { get; private set; }

        /// <summary>
        /// Customer&#39;s state or province. Required for US and Canadian customers.
        /// </summary>
        /// <value>Customer&#39;s state or province. Required for US and Canadian customers.</value>
        /* <example>New York</example> */
        [JsonPropertyName("customer_province")]
        public string CustomerProvince { get { return this.CustomerProvinceOption; } set { this.CustomerProvinceOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomerProvinceISO
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerProvinceISOOption { get; private set; }

        /// <summary>
        /// Customer&#39;s state or province ISO code. Used for automated tax calculations.
        /// </summary>
        /// <value>Customer&#39;s state or province ISO code. Used for automated tax calculations.</value>
        /* <example>NY</example> */
        [JsonPropertyName("customer_provinceISO")]
        public string CustomerProvinceISO { get { return this.CustomerProvinceISOOption; } set { this.CustomerProvinceISOOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PhoneNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhoneNumberOption { get; private set; }

        /// <summary>
        /// Customer&#39;s phone number with country code. Used for SMS notifications and verification.
        /// </summary>
        /// <value>Customer&#39;s phone number with country code. Used for SMS notifications and verification.</value>
        /* <example>+1-555-123-4567</example> */
        [JsonPropertyName("phoneNumber")]
        public string PhoneNumber { get { return this.PhoneNumberOption; } set { this.PhoneNumberOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateStablePaymentIntentDto {\n");
            sb.Append("  SourceCurrency: ").Append(SourceCurrency).Append("\n");
            sb.Append("  SourceNetwork: ").Append(SourceNetwork).Append("\n");
            sb.Append("  DestinationNetwork: ").Append(DestinationNetwork).Append("\n");
            sb.Append("  DestinationCurrency: ").Append(DestinationCurrency).Append("\n");
            sb.Append("  DestinationAddress: ").Append(DestinationAddress).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  CustomerFirstName: ").Append(CustomerFirstName).Append("\n");
            sb.Append("  CustomerLastName: ").Append(CustomerLastName).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  CustomerAddress: ").Append(CustomerAddress).Append("\n");
            sb.Append("  CustomerCountry: ").Append(CustomerCountry).Append("\n");
            sb.Append("  CustomerCountryISO: ").Append(CustomerCountryISO).Append("\n");
            sb.Append("  CustomerProvince: ").Append(CustomerProvince).Append("\n");
            sb.Append("  CustomerProvinceISO: ").Append(CustomerProvinceISO).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.AmountOption.Value != null) {
                // Amount (string) pattern
                Regex regexAmount = new Regex(@"^\d+(\.\d{1,6})?$", RegexOptions.CultureInvariant);

                if (this.AmountOption.Value != null &&!regexAmount.Match(this.AmountOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must match a pattern of " + regexAmount, new [] { "Amount" });
                }
            }

            // CustomerFirstName (string) maxLength
            if (this.CustomerFirstName != null && this.CustomerFirstName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CustomerFirstName, length must be less than 100.", new [] { "CustomerFirstName" });
            }

            // CustomerLastName (string) maxLength
            if (this.CustomerLastName != null && this.CustomerLastName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CustomerLastName, length must be less than 100.", new [] { "CustomerLastName" });
            }

            // CustomerEmail (string) maxLength
            if (this.CustomerEmail != null && this.CustomerEmail.Length > 255)
            {
                yield return new ValidationResult("Invalid value for CustomerEmail, length must be less than 255.", new [] { "CustomerEmail" });
            }

            // CustomerAddress (string) maxLength
            if (this.CustomerAddress != null && this.CustomerAddress.Length > 500)
            {
                yield return new ValidationResult("Invalid value for CustomerAddress, length must be less than 500.", new [] { "CustomerAddress" });
            }

            // CustomerCountry (string) maxLength
            if (this.CustomerCountry != null && this.CustomerCountry.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CustomerCountry, length must be less than 100.", new [] { "CustomerCountry" });
            }

            // CustomerCountryISO (string) maxLength
            if (this.CustomerCountryISO != null && this.CustomerCountryISO.Length > 2)
            {
                yield return new ValidationResult("Invalid value for CustomerCountryISO, length must be less than 2.", new [] { "CustomerCountryISO" });
            }

            if (this.CustomerCountryISOOption.Value != null) {
                // CustomerCountryISO (string) pattern
                Regex regexCustomerCountryISO = new Regex(@"^[A-Z]{2}$", RegexOptions.CultureInvariant);

                if (this.CustomerCountryISOOption.Value != null &&!regexCustomerCountryISO.Match(this.CustomerCountryISOOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CustomerCountryISO, must match a pattern of " + regexCustomerCountryISO, new [] { "CustomerCountryISO" });
                }
            }

            // CustomerProvince (string) maxLength
            if (this.CustomerProvince != null && this.CustomerProvince.Length > 100)
            {
                yield return new ValidationResult("Invalid value for CustomerProvince, length must be less than 100.", new [] { "CustomerProvince" });
            }

            // CustomerProvinceISO (string) maxLength
            if (this.CustomerProvinceISO != null && this.CustomerProvinceISO.Length > 10)
            {
                yield return new ValidationResult("Invalid value for CustomerProvinceISO, length must be less than 10.", new [] { "CustomerProvinceISO" });
            }

            // PhoneNumber (string) maxLength
            if (this.PhoneNumber != null && this.PhoneNumber.Length > 20)
            {
                yield return new ValidationResult("Invalid value for PhoneNumber, length must be less than 20.", new [] { "PhoneNumber" });
            }

            if (this.PhoneNumberOption.Value != null) {
                // PhoneNumber (string) pattern
                Regex regexPhoneNumber = new Regex(@"^[+]?[\d\s\-\(\)]+$", RegexOptions.CultureInvariant);

                if (this.PhoneNumberOption.Value != null &&!regexPhoneNumber.Match(this.PhoneNumberOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, must match a pattern of " + regexPhoneNumber, new [] { "PhoneNumber" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateStablePaymentIntentDto" />
    /// </summary>
    public class CreateStablePaymentIntentDtoJsonConverter : JsonConverter<CreateStablePaymentIntentDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateStablePaymentIntentDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateStablePaymentIntentDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<StableCoinCurrency?> sourceCurrency = default;
            Option<BridgePaymentRail?> sourceNetwork = default;
            Option<BridgePaymentRail?> destinationNetwork = default;
            Option<StableCoinCurrency?> destinationCurrency = default;
            Option<string> destinationAddress = default;
            Option<string> amount = default;
            Option<string> customerFirstName = default;
            Option<string> customerLastName = default;
            Option<string> customerEmail = default;
            Option<string> customerAddress = default;
            Option<string> customerCountry = default;
            Option<string> customerCountryISO = default;
            Option<string> customerProvince = default;
            Option<string> customerProvinceISO = default;
            Option<string> phoneNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sourceCurrency":
                            string sourceCurrencyRawValue = utf8JsonReader.GetString();
                            if (sourceCurrencyRawValue != null)
                                sourceCurrency = new Option<StableCoinCurrency?>(StableCoinCurrencyValueConverter.FromStringOrDefault(sourceCurrencyRawValue));
                            break;
                        case "sourceNetwork":
                            string sourceNetworkRawValue = utf8JsonReader.GetString();
                            if (sourceNetworkRawValue != null)
                                sourceNetwork = new Option<BridgePaymentRail?>(BridgePaymentRailValueConverter.FromStringOrDefault(sourceNetworkRawValue));
                            break;
                        case "destinationNetwork":
                            string destinationNetworkRawValue = utf8JsonReader.GetString();
                            if (destinationNetworkRawValue != null)
                                destinationNetwork = new Option<BridgePaymentRail?>(BridgePaymentRailValueConverter.FromStringOrDefault(destinationNetworkRawValue));
                            break;
                        case "destinationCurrency":
                            string destinationCurrencyRawValue = utf8JsonReader.GetString();
                            if (destinationCurrencyRawValue != null)
                                destinationCurrency = new Option<StableCoinCurrency?>(StableCoinCurrencyValueConverter.FromStringOrDefault(destinationCurrencyRawValue));
                            break;
                        case "destinationAddress":
                            destinationAddress = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_first_name":
                            customerFirstName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_last_name":
                            customerLastName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_email":
                            customerEmail = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_address":
                            customerAddress = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_country":
                            customerCountry = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_countryISO":
                            customerCountryISO = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_province":
                            customerProvince = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_provinceISO":
                            customerProvinceISO = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phoneNumber":
                            phoneNumber = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sourceCurrency.IsSet)
                throw new ArgumentException("Property is required for class CreateStablePaymentIntentDto.", nameof(sourceCurrency));

            if (!sourceNetwork.IsSet)
                throw new ArgumentException("Property is required for class CreateStablePaymentIntentDto.", nameof(sourceNetwork));

            if (!destinationNetwork.IsSet)
                throw new ArgumentException("Property is required for class CreateStablePaymentIntentDto.", nameof(destinationNetwork));

            if (sourceCurrency.IsSet && sourceCurrency.Value == null)
                throw new ArgumentNullException(nameof(sourceCurrency), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (sourceNetwork.IsSet && sourceNetwork.Value == null)
                throw new ArgumentNullException(nameof(sourceNetwork), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (destinationNetwork.IsSet && destinationNetwork.Value == null)
                throw new ArgumentNullException(nameof(destinationNetwork), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (destinationCurrency.IsSet && destinationCurrency.Value == null)
                throw new ArgumentNullException(nameof(destinationCurrency), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (destinationAddress.IsSet && destinationAddress.Value == null)
                throw new ArgumentNullException(nameof(destinationAddress), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerFirstName.IsSet && customerFirstName.Value == null)
                throw new ArgumentNullException(nameof(customerFirstName), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerLastName.IsSet && customerLastName.Value == null)
                throw new ArgumentNullException(nameof(customerLastName), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerEmail.IsSet && customerEmail.Value == null)
                throw new ArgumentNullException(nameof(customerEmail), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerAddress.IsSet && customerAddress.Value == null)
                throw new ArgumentNullException(nameof(customerAddress), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerCountry.IsSet && customerCountry.Value == null)
                throw new ArgumentNullException(nameof(customerCountry), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerCountryISO.IsSet && customerCountryISO.Value == null)
                throw new ArgumentNullException(nameof(customerCountryISO), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerProvince.IsSet && customerProvince.Value == null)
                throw new ArgumentNullException(nameof(customerProvince), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (customerProvinceISO.IsSet && customerProvinceISO.Value == null)
                throw new ArgumentNullException(nameof(customerProvinceISO), "Property is not nullable for class CreateStablePaymentIntentDto.");

            if (phoneNumber.IsSet && phoneNumber.Value == null)
                throw new ArgumentNullException(nameof(phoneNumber), "Property is not nullable for class CreateStablePaymentIntentDto.");

            return new CreateStablePaymentIntentDto(sourceCurrency.Value.Value, sourceNetwork.Value.Value, destinationNetwork.Value.Value, destinationCurrency, destinationAddress, amount, customerFirstName, customerLastName, customerEmail, customerAddress, customerCountry, customerCountryISO, customerProvince, customerProvinceISO, phoneNumber);
        }

        /// <summary>
        /// Serializes a <see cref="CreateStablePaymentIntentDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateStablePaymentIntentDto createStablePaymentIntentDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createStablePaymentIntentDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateStablePaymentIntentDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createStablePaymentIntentDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateStablePaymentIntentDto createStablePaymentIntentDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createStablePaymentIntentDto.DestinationAddressOption.IsSet && createStablePaymentIntentDto.DestinationAddress == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.DestinationAddress), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.AmountOption.IsSet && createStablePaymentIntentDto.Amount == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.Amount), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerFirstNameOption.IsSet && createStablePaymentIntentDto.CustomerFirstName == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerFirstName), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerLastNameOption.IsSet && createStablePaymentIntentDto.CustomerLastName == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerLastName), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerEmailOption.IsSet && createStablePaymentIntentDto.CustomerEmail == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerEmail), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerAddressOption.IsSet && createStablePaymentIntentDto.CustomerAddress == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerAddress), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerCountryOption.IsSet && createStablePaymentIntentDto.CustomerCountry == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerCountry), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerCountryISOOption.IsSet && createStablePaymentIntentDto.CustomerCountryISO == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerCountryISO), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerProvinceOption.IsSet && createStablePaymentIntentDto.CustomerProvince == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerProvince), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.CustomerProvinceISOOption.IsSet && createStablePaymentIntentDto.CustomerProvinceISO == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.CustomerProvinceISO), "Property is required for class CreateStablePaymentIntentDto.");

            if (createStablePaymentIntentDto.PhoneNumberOption.IsSet && createStablePaymentIntentDto.PhoneNumber == null)
                throw new ArgumentNullException(nameof(createStablePaymentIntentDto.PhoneNumber), "Property is required for class CreateStablePaymentIntentDto.");

            var sourceCurrencyRawValue = StableCoinCurrencyValueConverter.ToJsonValue(createStablePaymentIntentDto.SourceCurrency);
            writer.WriteString("sourceCurrency", sourceCurrencyRawValue);

            var sourceNetworkRawValue = BridgePaymentRailValueConverter.ToJsonValue(createStablePaymentIntentDto.SourceNetwork);
            writer.WriteString("sourceNetwork", sourceNetworkRawValue);

            var destinationNetworkRawValue = BridgePaymentRailValueConverter.ToJsonValue(createStablePaymentIntentDto.DestinationNetwork);
            writer.WriteString("destinationNetwork", destinationNetworkRawValue);

            if (createStablePaymentIntentDto.DestinationCurrencyOption.IsSet)
            {
                var destinationCurrencyRawValue = StableCoinCurrencyValueConverter.ToJsonValue(createStablePaymentIntentDto.DestinationCurrency.Value);
                writer.WriteString("destinationCurrency", destinationCurrencyRawValue);
            }
            if (createStablePaymentIntentDto.DestinationAddressOption.IsSet)
                writer.WriteString("destinationAddress", createStablePaymentIntentDto.DestinationAddress);

            if (createStablePaymentIntentDto.AmountOption.IsSet)
                writer.WriteString("amount", createStablePaymentIntentDto.Amount);

            if (createStablePaymentIntentDto.CustomerFirstNameOption.IsSet)
                writer.WriteString("customer_first_name", createStablePaymentIntentDto.CustomerFirstName);

            if (createStablePaymentIntentDto.CustomerLastNameOption.IsSet)
                writer.WriteString("customer_last_name", createStablePaymentIntentDto.CustomerLastName);

            if (createStablePaymentIntentDto.CustomerEmailOption.IsSet)
                writer.WriteString("customer_email", createStablePaymentIntentDto.CustomerEmail);

            if (createStablePaymentIntentDto.CustomerAddressOption.IsSet)
                writer.WriteString("customer_address", createStablePaymentIntentDto.CustomerAddress);

            if (createStablePaymentIntentDto.CustomerCountryOption.IsSet)
                writer.WriteString("customer_country", createStablePaymentIntentDto.CustomerCountry);

            if (createStablePaymentIntentDto.CustomerCountryISOOption.IsSet)
                writer.WriteString("customer_countryISO", createStablePaymentIntentDto.CustomerCountryISO);

            if (createStablePaymentIntentDto.CustomerProvinceOption.IsSet)
                writer.WriteString("customer_province", createStablePaymentIntentDto.CustomerProvince);

            if (createStablePaymentIntentDto.CustomerProvinceISOOption.IsSet)
                writer.WriteString("customer_provinceISO", createStablePaymentIntentDto.CustomerProvinceISO);

            if (createStablePaymentIntentDto.PhoneNumberOption.IsSet)
                writer.WriteString("phoneNumber", createStablePaymentIntentDto.PhoneNumber);
        }
    }
}
