// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// CreateLiquidationAddressDto
    /// </summary>
    public partial class CreateLiquidationAddressDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLiquidationAddressDto" /> class.
        /// </summary>
        /// <param name="chain">The blockchain chain for the liquidation address</param>
        /// <param name="currency">The currency for the liquidation address</param>
        /// <param name="address">The liquidation address on the blockchain</param>
        /// <param name="externalAccountId">External bank account to send funds to</param>
        /// <param name="prefundedAccountId">Developer&#39;s prefunded account id</param>
        /// <param name="bridgeWalletId">Bridge Wallet to send funds to</param>
        /// <param name="destinationPaymentRail">Payment rail for sending funds</param>
        /// <param name="destinationCurrency">Currency for sending funds</param>
        /// <param name="destinationWireMessage">Message for wire transfers</param>
        /// <param name="destinationSepaReference">Reference for SEPA transactions</param>
        /// <param name="destinationAchReference">Reference for ACH transactions</param>
        /// <param name="destinationAddress">Crypto wallet address for crypto transfers</param>
        /// <param name="destinationBlockchainMemo">Memo for blockchain transactions</param>
        /// <param name="returnAddress">Address to return funds on failed transactions (Not supported on Stellar)</param>
        /// <param name="customDeveloperFeePercent">Custom developer fee percentage (Base 100 percentage: 10.2% &#x3D; \&quot;10.2\&quot;)</param>
        [JsonConstructor]
        public CreateLiquidationAddressDto(ChainEnum chain, CurrencyEnum currency, string address, Option<string> externalAccountId = default, Option<string> prefundedAccountId = default, Option<string> bridgeWalletId = default, Option<BridgePaymentRail?> destinationPaymentRail = default, Option<DestinationCurrency?> destinationCurrency = default, Option<string> destinationWireMessage = default, Option<string> destinationSepaReference = default, Option<string> destinationAchReference = default, Option<string> destinationAddress = default, Option<string> destinationBlockchainMemo = default, Option<string> returnAddress = default, Option<string> customDeveloperFeePercent = default)
        {
            Chain = chain;
            Currency = currency;
            Address = address;
            ExternalAccountIdOption = externalAccountId;
            PrefundedAccountIdOption = prefundedAccountId;
            BridgeWalletIdOption = bridgeWalletId;
            DestinationPaymentRailOption = destinationPaymentRail;
            DestinationCurrencyOption = destinationCurrency;
            DestinationWireMessageOption = destinationWireMessage;
            DestinationSepaReferenceOption = destinationSepaReference;
            DestinationAchReferenceOption = destinationAchReference;
            DestinationAddressOption = destinationAddress;
            DestinationBlockchainMemoOption = destinationBlockchainMemo;
            ReturnAddressOption = returnAddress;
            CustomDeveloperFeePercentOption = customDeveloperFeePercent;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The blockchain chain for the liquidation address
        /// </summary>
        /// <value>The blockchain chain for the liquidation address</value>
        public enum ChainEnum
        {
            /// <summary>
            /// Enum Ethereum for value: ethereum
            /// </summary>
            Ethereum = 1,

            /// <summary>
            /// Enum Solana for value: solana
            /// </summary>
            Solana = 2,

            /// <summary>
            /// Enum Polygon for value: polygon
            /// </summary>
            Polygon = 3,

            /// <summary>
            /// Enum AvalancheCChain for value: avalanche_c_chain
            /// </summary>
            AvalancheCChain = 4,

            /// <summary>
            /// Enum Base for value: base
            /// </summary>
            Base = 5,

            /// <summary>
            /// Enum Arbitrum for value: arbitrum
            /// </summary>
            Arbitrum = 6,

            /// <summary>
            /// Enum Optimism for value: optimism
            /// </summary>
            Optimism = 7,

            /// <summary>
            /// Enum Stellar for value: stellar
            /// </summary>
            Stellar = 8,

            /// <summary>
            /// Enum Tron for value: tron
            /// </summary>
            Tron = 9
        }

        /// <summary>
        /// Returns a <see cref="ChainEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ChainEnum ChainEnumFromString(string value)
        {
            if (value.Equals("ethereum"))
                return ChainEnum.Ethereum;

            if (value.Equals("solana"))
                return ChainEnum.Solana;

            if (value.Equals("polygon"))
                return ChainEnum.Polygon;

            if (value.Equals("avalanche_c_chain"))
                return ChainEnum.AvalancheCChain;

            if (value.Equals("base"))
                return ChainEnum.Base;

            if (value.Equals("arbitrum"))
                return ChainEnum.Arbitrum;

            if (value.Equals("optimism"))
                return ChainEnum.Optimism;

            if (value.Equals("stellar"))
                return ChainEnum.Stellar;

            if (value.Equals("tron"))
                return ChainEnum.Tron;

            throw new NotImplementedException($"Could not convert value to type ChainEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ChainEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ChainEnum? ChainEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ethereum"))
                return ChainEnum.Ethereum;

            if (value.Equals("solana"))
                return ChainEnum.Solana;

            if (value.Equals("polygon"))
                return ChainEnum.Polygon;

            if (value.Equals("avalanche_c_chain"))
                return ChainEnum.AvalancheCChain;

            if (value.Equals("base"))
                return ChainEnum.Base;

            if (value.Equals("arbitrum"))
                return ChainEnum.Arbitrum;

            if (value.Equals("optimism"))
                return ChainEnum.Optimism;

            if (value.Equals("stellar"))
                return ChainEnum.Stellar;

            if (value.Equals("tron"))
                return ChainEnum.Tron;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ChainEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ChainEnumToJsonValue(ChainEnum value)
        {
            if (value == ChainEnum.Ethereum)
                return "ethereum";

            if (value == ChainEnum.Solana)
                return "solana";

            if (value == ChainEnum.Polygon)
                return "polygon";

            if (value == ChainEnum.AvalancheCChain)
                return "avalanche_c_chain";

            if (value == ChainEnum.Base)
                return "base";

            if (value == ChainEnum.Arbitrum)
                return "arbitrum";

            if (value == ChainEnum.Optimism)
                return "optimism";

            if (value == ChainEnum.Stellar)
                return "stellar";

            if (value == ChainEnum.Tron)
                return "tron";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The blockchain chain for the liquidation address
        /// </summary>
        /// <value>The blockchain chain for the liquidation address</value>
        /* <example>ethereum</example> */
        [JsonPropertyName("chain")]
        public ChainEnum Chain { get; set; }

        /// <summary>
        /// The currency for the liquidation address
        /// </summary>
        /// <value>The currency for the liquidation address</value>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum Usdc for value: usdc
            /// </summary>
            Usdc = 1,

            /// <summary>
            /// Enum Eurc for value: eurc
            /// </summary>
            Eurc = 2,

            /// <summary>
            /// Enum Dai for value: dai
            /// </summary>
            Dai = 3,

            /// <summary>
            /// Enum Pyusd for value: pyusd
            /// </summary>
            Pyusd = 4,

            /// <summary>
            /// Enum Usdt for value: usdt
            /// </summary>
            Usdt = 5
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("usdc"))
                return CurrencyEnum.Usdc;

            if (value.Equals("eurc"))
                return CurrencyEnum.Eurc;

            if (value.Equals("dai"))
                return CurrencyEnum.Dai;

            if (value.Equals("pyusd"))
                return CurrencyEnum.Pyusd;

            if (value.Equals("usdt"))
                return CurrencyEnum.Usdt;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("usdc"))
                return CurrencyEnum.Usdc;

            if (value.Equals("eurc"))
                return CurrencyEnum.Eurc;

            if (value.Equals("dai"))
                return CurrencyEnum.Dai;

            if (value.Equals("pyusd"))
                return CurrencyEnum.Pyusd;

            if (value.Equals("usdt"))
                return CurrencyEnum.Usdt;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.Usdc)
                return "usdc";

            if (value == CurrencyEnum.Eurc)
                return "eurc";

            if (value == CurrencyEnum.Dai)
                return "dai";

            if (value == CurrencyEnum.Pyusd)
                return "pyusd";

            if (value == CurrencyEnum.Usdt)
                return "usdt";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The currency for the liquidation address
        /// </summary>
        /// <value>The currency for the liquidation address</value>
        /* <example>usdc</example> */
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Used to track the state of DestinationPaymentRail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BridgePaymentRail?> DestinationPaymentRailOption { get; private set; }

        /// <summary>
        /// Payment rail for sending funds
        /// </summary>
        /// <value>Payment rail for sending funds</value>
        [JsonPropertyName("destination_payment_rail")]
        public BridgePaymentRail? DestinationPaymentRail { get { return this.DestinationPaymentRailOption; } set { this.DestinationPaymentRailOption = new Option<BridgePaymentRail?>(value); } }

        /// <summary>
        /// Used to track the state of DestinationCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DestinationCurrency?> DestinationCurrencyOption { get; private set; }

        /// <summary>
        /// Currency for sending funds
        /// </summary>
        /// <value>Currency for sending funds</value>
        [JsonPropertyName("destination_currency")]
        public DestinationCurrency? DestinationCurrency { get { return this.DestinationCurrencyOption; } set { this.DestinationCurrencyOption = new Option<DestinationCurrency?>(value); } }

        /// <summary>
        /// The liquidation address on the blockchain
        /// </summary>
        /// <value>The liquidation address on the blockchain</value>
        /* <example>0x4d0280da2f2fDA5103914bCc5aad114743152A9c</example> */
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Used to track the state of ExternalAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ExternalAccountIdOption { get; private set; }

        /// <summary>
        /// External bank account to send funds to
        /// </summary>
        /// <value>External bank account to send funds to</value>
        /* <example>ext_123</example> */
        [JsonPropertyName("external_account_id")]
        public string ExternalAccountId { get { return this.ExternalAccountIdOption; } set { this.ExternalAccountIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PrefundedAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PrefundedAccountIdOption { get; private set; }

        /// <summary>
        /// Developer&#39;s prefunded account id
        /// </summary>
        /// <value>Developer&#39;s prefunded account id</value>
        /* <example>pf_acc_123</example> */
        [JsonPropertyName("prefunded_account_id")]
        public string PrefundedAccountId { get { return this.PrefundedAccountIdOption; } set { this.PrefundedAccountIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of BridgeWalletId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> BridgeWalletIdOption { get; private set; }

        /// <summary>
        /// Bridge Wallet to send funds to
        /// </summary>
        /// <value>Bridge Wallet to send funds to</value>
        /* <example>bw_123</example> */
        [JsonPropertyName("bridge_wallet_id")]
        public string BridgeWalletId { get { return this.BridgeWalletIdOption; } set { this.BridgeWalletIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DestinationWireMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationWireMessageOption { get; private set; }

        /// <summary>
        /// Message for wire transfers
        /// </summary>
        /// <value>Message for wire transfers</value>
        /* <example>Liquidation payment for customer</example> */
        [JsonPropertyName("destination_wire_message")]
        public string DestinationWireMessage { get { return this.DestinationWireMessageOption; } set { this.DestinationWireMessageOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DestinationSepaReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationSepaReferenceOption { get; private set; }

        /// <summary>
        /// Reference for SEPA transactions
        /// </summary>
        /// <value>Reference for SEPA transactions</value>
        /* <example>SEPA-REF-123456</example> */
        [JsonPropertyName("destination_sepa_reference")]
        public string DestinationSepaReference { get { return this.DestinationSepaReferenceOption; } set { this.DestinationSepaReferenceOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DestinationAchReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationAchReferenceOption { get; private set; }

        /// <summary>
        /// Reference for ACH transactions
        /// </summary>
        /// <value>Reference for ACH transactions</value>
        /* <example>ACH123</example> */
        [JsonPropertyName("destination_ach_reference")]
        public string DestinationAchReference { get { return this.DestinationAchReferenceOption; } set { this.DestinationAchReferenceOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DestinationAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationAddressOption { get; private set; }

        /// <summary>
        /// Crypto wallet address for crypto transfers
        /// </summary>
        /// <value>Crypto wallet address for crypto transfers</value>
        /* <example>0x1234567890abcdef1234567890abcdef12345678</example> */
        [JsonPropertyName("destination_address")]
        public string DestinationAddress { get { return this.DestinationAddressOption; } set { this.DestinationAddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DestinationBlockchainMemo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DestinationBlockchainMemoOption { get; private set; }

        /// <summary>
        /// Memo for blockchain transactions
        /// </summary>
        /// <value>Memo for blockchain transactions</value>
        /* <example>liquidation-memo-123</example> */
        [JsonPropertyName("destination_blockchain_memo")]
        public string DestinationBlockchainMemo { get { return this.DestinationBlockchainMemoOption; } set { this.DestinationBlockchainMemoOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of ReturnAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ReturnAddressOption { get; private set; }

        /// <summary>
        /// Address to return funds on failed transactions (Not supported on Stellar)
        /// </summary>
        /// <value>Address to return funds on failed transactions (Not supported on Stellar)</value>
        /* <example>0xabcdefabcdefabcdefabcdefabcdefabcdef</example> */
        [JsonPropertyName("return_address")]
        public string ReturnAddress { get { return this.ReturnAddressOption; } set { this.ReturnAddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CustomDeveloperFeePercent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomDeveloperFeePercentOption { get; private set; }

        /// <summary>
        /// Custom developer fee percentage (Base 100 percentage: 10.2% &#x3D; \&quot;10.2\&quot;)
        /// </summary>
        /// <value>Custom developer fee percentage (Base 100 percentage: 10.2% &#x3D; \&quot;10.2\&quot;)</value>
        /* <example>2.5</example> */
        [JsonPropertyName("custom_developer_fee_percent")]
        public string CustomDeveloperFeePercent { get { return this.CustomDeveloperFeePercentOption; } set { this.CustomDeveloperFeePercentOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateLiquidationAddressDto {\n");
            sb.Append("  Chain: ").Append(Chain).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  ExternalAccountId: ").Append(ExternalAccountId).Append("\n");
            sb.Append("  PrefundedAccountId: ").Append(PrefundedAccountId).Append("\n");
            sb.Append("  BridgeWalletId: ").Append(BridgeWalletId).Append("\n");
            sb.Append("  DestinationPaymentRail: ").Append(DestinationPaymentRail).Append("\n");
            sb.Append("  DestinationCurrency: ").Append(DestinationCurrency).Append("\n");
            sb.Append("  DestinationWireMessage: ").Append(DestinationWireMessage).Append("\n");
            sb.Append("  DestinationSepaReference: ").Append(DestinationSepaReference).Append("\n");
            sb.Append("  DestinationAchReference: ").Append(DestinationAchReference).Append("\n");
            sb.Append("  DestinationAddress: ").Append(DestinationAddress).Append("\n");
            sb.Append("  DestinationBlockchainMemo: ").Append(DestinationBlockchainMemo).Append("\n");
            sb.Append("  ReturnAddress: ").Append(ReturnAddress).Append("\n");
            sb.Append("  CustomDeveloperFeePercent: ").Append(CustomDeveloperFeePercent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ExternalAccountId (string) maxLength
            if (this.ExternalAccountId != null && this.ExternalAccountId.Length > 42)
            {
                yield return new ValidationResult("Invalid value for ExternalAccountId, length must be less than 42.", new [] { "ExternalAccountId" });
            }

            // PrefundedAccountId (string) maxLength
            if (this.PrefundedAccountId != null && this.PrefundedAccountId.Length > 42)
            {
                yield return new ValidationResult("Invalid value for PrefundedAccountId, length must be less than 42.", new [] { "PrefundedAccountId" });
            }

            // BridgeWalletId (string) maxLength
            if (this.BridgeWalletId != null && this.BridgeWalletId.Length > 42)
            {
                yield return new ValidationResult("Invalid value for BridgeWalletId, length must be less than 42.", new [] { "BridgeWalletId" });
            }

            // DestinationWireMessage (string) maxLength
            if (this.DestinationWireMessage != null && this.DestinationWireMessage.Length > 256)
            {
                yield return new ValidationResult("Invalid value for DestinationWireMessage, length must be less than 256.", new [] { "DestinationWireMessage" });
            }

            // DestinationSepaReference (string) maxLength
            if (this.DestinationSepaReference != null && this.DestinationSepaReference.Length > 140)
            {
                yield return new ValidationResult("Invalid value for DestinationSepaReference, length must be less than 140.", new [] { "DestinationSepaReference" });
            }

            // DestinationSepaReference (string) minLength
            if (this.DestinationSepaReference != null && this.DestinationSepaReference.Length < 6)
            {
                yield return new ValidationResult("Invalid value for DestinationSepaReference, length must be greater than 6.", new [] { "DestinationSepaReference" });
            }

            // DestinationAchReference (string) maxLength
            if (this.DestinationAchReference != null && this.DestinationAchReference.Length > 10)
            {
                yield return new ValidationResult("Invalid value for DestinationAchReference, length must be less than 10.", new [] { "DestinationAchReference" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateLiquidationAddressDto" />
    /// </summary>
    public class CreateLiquidationAddressDtoJsonConverter : JsonConverter<CreateLiquidationAddressDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateLiquidationAddressDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateLiquidationAddressDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CreateLiquidationAddressDto.ChainEnum?> chain = default;
            Option<CreateLiquidationAddressDto.CurrencyEnum?> currency = default;
            Option<string> address = default;
            Option<string> externalAccountId = default;
            Option<string> prefundedAccountId = default;
            Option<string> bridgeWalletId = default;
            Option<BridgePaymentRail?> destinationPaymentRail = default;
            Option<DestinationCurrency?> destinationCurrency = default;
            Option<string> destinationWireMessage = default;
            Option<string> destinationSepaReference = default;
            Option<string> destinationAchReference = default;
            Option<string> destinationAddress = default;
            Option<string> destinationBlockchainMemo = default;
            Option<string> returnAddress = default;
            Option<string> customDeveloperFeePercent = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "chain":
                            string chainRawValue = utf8JsonReader.GetString();
                            if (chainRawValue != null)
                                chain = new Option<CreateLiquidationAddressDto.ChainEnum?>(CreateLiquidationAddressDto.ChainEnumFromStringOrDefault(chainRawValue));
                            break;
                        case "currency":
                            string currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                                currency = new Option<CreateLiquidationAddressDto.CurrencyEnum?>(CreateLiquidationAddressDto.CurrencyEnumFromStringOrDefault(currencyRawValue));
                            break;
                        case "address":
                            address = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "external_account_id":
                            externalAccountId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "prefunded_account_id":
                            prefundedAccountId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "bridge_wallet_id":
                            bridgeWalletId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destination_payment_rail":
                            string destinationPaymentRailRawValue = utf8JsonReader.GetString();
                            if (destinationPaymentRailRawValue != null)
                                destinationPaymentRail = new Option<BridgePaymentRail?>(BridgePaymentRailValueConverter.FromStringOrDefault(destinationPaymentRailRawValue));
                            break;
                        case "destination_currency":
                            string destinationCurrencyRawValue = utf8JsonReader.GetString();
                            if (destinationCurrencyRawValue != null)
                                destinationCurrency = new Option<DestinationCurrency?>(DestinationCurrencyValueConverter.FromStringOrDefault(destinationCurrencyRawValue));
                            break;
                        case "destination_wire_message":
                            destinationWireMessage = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destination_sepa_reference":
                            destinationSepaReference = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destination_ach_reference":
                            destinationAchReference = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destination_address":
                            destinationAddress = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "destination_blockchain_memo":
                            destinationBlockchainMemo = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "return_address":
                            returnAddress = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "custom_developer_fee_percent":
                            customDeveloperFeePercent = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!chain.IsSet)
                throw new ArgumentException("Property is required for class CreateLiquidationAddressDto.", nameof(chain));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class CreateLiquidationAddressDto.", nameof(currency));

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class CreateLiquidationAddressDto.", nameof(address));

            if (chain.IsSet && chain.Value == null)
                throw new ArgumentNullException(nameof(chain), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (externalAccountId.IsSet && externalAccountId.Value == null)
                throw new ArgumentNullException(nameof(externalAccountId), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (prefundedAccountId.IsSet && prefundedAccountId.Value == null)
                throw new ArgumentNullException(nameof(prefundedAccountId), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (bridgeWalletId.IsSet && bridgeWalletId.Value == null)
                throw new ArgumentNullException(nameof(bridgeWalletId), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationPaymentRail.IsSet && destinationPaymentRail.Value == null)
                throw new ArgumentNullException(nameof(destinationPaymentRail), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationCurrency.IsSet && destinationCurrency.Value == null)
                throw new ArgumentNullException(nameof(destinationCurrency), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationWireMessage.IsSet && destinationWireMessage.Value == null)
                throw new ArgumentNullException(nameof(destinationWireMessage), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationSepaReference.IsSet && destinationSepaReference.Value == null)
                throw new ArgumentNullException(nameof(destinationSepaReference), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationAchReference.IsSet && destinationAchReference.Value == null)
                throw new ArgumentNullException(nameof(destinationAchReference), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationAddress.IsSet && destinationAddress.Value == null)
                throw new ArgumentNullException(nameof(destinationAddress), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (destinationBlockchainMemo.IsSet && destinationBlockchainMemo.Value == null)
                throw new ArgumentNullException(nameof(destinationBlockchainMemo), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (returnAddress.IsSet && returnAddress.Value == null)
                throw new ArgumentNullException(nameof(returnAddress), "Property is not nullable for class CreateLiquidationAddressDto.");

            if (customDeveloperFeePercent.IsSet && customDeveloperFeePercent.Value == null)
                throw new ArgumentNullException(nameof(customDeveloperFeePercent), "Property is not nullable for class CreateLiquidationAddressDto.");

            return new CreateLiquidationAddressDto(chain.Value.Value, currency.Value.Value, address.Value, externalAccountId, prefundedAccountId, bridgeWalletId, destinationPaymentRail, destinationCurrency, destinationWireMessage, destinationSepaReference, destinationAchReference, destinationAddress, destinationBlockchainMemo, returnAddress, customDeveloperFeePercent);
        }

        /// <summary>
        /// Serializes a <see cref="CreateLiquidationAddressDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLiquidationAddressDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateLiquidationAddressDto createLiquidationAddressDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createLiquidationAddressDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateLiquidationAddressDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLiquidationAddressDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateLiquidationAddressDto createLiquidationAddressDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createLiquidationAddressDto.Address == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.Address), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.ExternalAccountIdOption.IsSet && createLiquidationAddressDto.ExternalAccountId == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.ExternalAccountId), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.PrefundedAccountIdOption.IsSet && createLiquidationAddressDto.PrefundedAccountId == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.PrefundedAccountId), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.BridgeWalletIdOption.IsSet && createLiquidationAddressDto.BridgeWalletId == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.BridgeWalletId), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.DestinationWireMessageOption.IsSet && createLiquidationAddressDto.DestinationWireMessage == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.DestinationWireMessage), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.DestinationSepaReferenceOption.IsSet && createLiquidationAddressDto.DestinationSepaReference == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.DestinationSepaReference), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.DestinationAchReferenceOption.IsSet && createLiquidationAddressDto.DestinationAchReference == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.DestinationAchReference), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.DestinationAddressOption.IsSet && createLiquidationAddressDto.DestinationAddress == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.DestinationAddress), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.DestinationBlockchainMemoOption.IsSet && createLiquidationAddressDto.DestinationBlockchainMemo == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.DestinationBlockchainMemo), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.ReturnAddressOption.IsSet && createLiquidationAddressDto.ReturnAddress == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.ReturnAddress), "Property is required for class CreateLiquidationAddressDto.");

            if (createLiquidationAddressDto.CustomDeveloperFeePercentOption.IsSet && createLiquidationAddressDto.CustomDeveloperFeePercent == null)
                throw new ArgumentNullException(nameof(createLiquidationAddressDto.CustomDeveloperFeePercent), "Property is required for class CreateLiquidationAddressDto.");

            var chainRawValue = CreateLiquidationAddressDto.ChainEnumToJsonValue(createLiquidationAddressDto.Chain);
            writer.WriteString("chain", chainRawValue);
            var currencyRawValue = CreateLiquidationAddressDto.CurrencyEnumToJsonValue(createLiquidationAddressDto.Currency);
            writer.WriteString("currency", currencyRawValue);
            writer.WriteString("address", createLiquidationAddressDto.Address);

            if (createLiquidationAddressDto.ExternalAccountIdOption.IsSet)
                writer.WriteString("external_account_id", createLiquidationAddressDto.ExternalAccountId);

            if (createLiquidationAddressDto.PrefundedAccountIdOption.IsSet)
                writer.WriteString("prefunded_account_id", createLiquidationAddressDto.PrefundedAccountId);

            if (createLiquidationAddressDto.BridgeWalletIdOption.IsSet)
                writer.WriteString("bridge_wallet_id", createLiquidationAddressDto.BridgeWalletId);

            if (createLiquidationAddressDto.DestinationPaymentRailOption.IsSet)
            {
                var destinationPaymentRailRawValue = BridgePaymentRailValueConverter.ToJsonValue(createLiquidationAddressDto.DestinationPaymentRail.Value);
                writer.WriteString("destination_payment_rail", destinationPaymentRailRawValue);
            }
            if (createLiquidationAddressDto.DestinationCurrencyOption.IsSet)
            {
                var destinationCurrencyRawValue = DestinationCurrencyValueConverter.ToJsonValue(createLiquidationAddressDto.DestinationCurrency.Value);
                writer.WriteString("destination_currency", destinationCurrencyRawValue);
            }
            if (createLiquidationAddressDto.DestinationWireMessageOption.IsSet)
                writer.WriteString("destination_wire_message", createLiquidationAddressDto.DestinationWireMessage);

            if (createLiquidationAddressDto.DestinationSepaReferenceOption.IsSet)
                writer.WriteString("destination_sepa_reference", createLiquidationAddressDto.DestinationSepaReference);

            if (createLiquidationAddressDto.DestinationAchReferenceOption.IsSet)
                writer.WriteString("destination_ach_reference", createLiquidationAddressDto.DestinationAchReference);

            if (createLiquidationAddressDto.DestinationAddressOption.IsSet)
                writer.WriteString("destination_address", createLiquidationAddressDto.DestinationAddress);

            if (createLiquidationAddressDto.DestinationBlockchainMemoOption.IsSet)
                writer.WriteString("destination_blockchain_memo", createLiquidationAddressDto.DestinationBlockchainMemo);

            if (createLiquidationAddressDto.ReturnAddressOption.IsSet)
                writer.WriteString("return_address", createLiquidationAddressDto.ReturnAddress);

            if (createLiquidationAddressDto.CustomDeveloperFeePercentOption.IsSet)
                writer.WriteString("custom_developer_fee_percent", createLiquidationAddressDto.CustomDeveloperFeePercent);
        }
    }
}
