// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// Current status of the customer account. Controls access to services and features.
    /// </summary>
    /// <value>Current status of the customer account. Controls access to services and features.</value>
    public enum CustomerStatus
    {
        /// <summary>
        /// Enum ACTIVE for value: ACTIVE
        /// </summary>
        ACTIVE = 1,

        /// <summary>
        /// Enum BLACKLISTED for value: BLACKLISTED
        /// </summary>
        BLACKLISTED = 2,

        /// <summary>
        /// Enum DEACTIVATED for value: DEACTIVATED
        /// </summary>
        DEACTIVATED = 3,

        /// <summary>
        /// Enum DELETED for value: DELETED
        /// </summary>
        DELETED = 4
    }

    /// <summary>
    /// Converts <see cref="CustomerStatus"/> to and from the JSON value
    /// </summary>
    public static class CustomerStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CustomerStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CustomerStatus FromString(string value)
        {
            if (value.Equals("ACTIVE"))
                return CustomerStatus.ACTIVE;

            if (value.Equals("BLACKLISTED"))
                return CustomerStatus.BLACKLISTED;

            if (value.Equals("DEACTIVATED"))
                return CustomerStatus.DEACTIVATED;

            if (value.Equals("DELETED"))
                return CustomerStatus.DELETED;

            throw new NotImplementedException($"Could not convert value to type CustomerStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CustomerStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CustomerStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("ACTIVE"))
                return CustomerStatus.ACTIVE;

            if (value.Equals("BLACKLISTED"))
                return CustomerStatus.BLACKLISTED;

            if (value.Equals("DEACTIVATED"))
                return CustomerStatus.DEACTIVATED;

            if (value.Equals("DELETED"))
                return CustomerStatus.DELETED;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CustomerStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(CustomerStatus value)
        {
            if (value == CustomerStatus.ACTIVE)
                return "ACTIVE";

            if (value == CustomerStatus.BLACKLISTED)
                return "BLACKLISTED";

            if (value == CustomerStatus.DEACTIVATED)
                return "DEACTIVATED";

            if (value == CustomerStatus.DELETED)
                return "DELETED";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomerStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CustomerStatusJsonConverter : JsonConverter<CustomerStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CustomerStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            CustomerStatus? result = rawValue == null
                ? null
                : CustomerStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CustomerStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customerStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CustomerStatus customerStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(CustomerStatusValueConverter.ToJsonValue(customerStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomerStatus"/>
    /// </summary>
    public class CustomerStatusNullableJsonConverter : JsonConverter<CustomerStatus?>
    {
        /// <summary>
        /// Returns a CustomerStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CustomerStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            CustomerStatus? result = rawValue == null
                ? null
                : CustomerStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CustomerStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customerStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CustomerStatus? customerStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(customerStatus.HasValue ? CustomerStatusValueConverter.ToJsonValue(customerStatus.Value).ToString() : "null");
        }
    }
}
