// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// Currency for sending funds
    /// </summary>
    /// <value>Currency for sending funds</value>
    public enum DestinationCurrency
    {
        /// <summary>
        /// Enum Usd for value: usd
        /// </summary>
        Usd = 1,

        /// <summary>
        /// Enum Eur for value: eur
        /// </summary>
        Eur = 2,

        /// <summary>
        /// Enum Mxn for value: mxn
        /// </summary>
        Mxn = 3,

        /// <summary>
        /// Enum Usdc for value: usdc
        /// </summary>
        Usdc = 4,

        /// <summary>
        /// Enum Eurc for value: eurc
        /// </summary>
        Eurc = 5,

        /// <summary>
        /// Enum Dai for value: dai
        /// </summary>
        Dai = 6,

        /// <summary>
        /// Enum Pyusd for value: pyusd
        /// </summary>
        Pyusd = 7,

        /// <summary>
        /// Enum Usdt for value: usdt
        /// </summary>
        Usdt = 8
    }

    /// <summary>
    /// Converts <see cref="DestinationCurrency"/> to and from the JSON value
    /// </summary>
    public static class DestinationCurrencyValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="DestinationCurrency"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DestinationCurrency FromString(string value)
        {
            if (value.Equals("usd"))
                return DestinationCurrency.Usd;

            if (value.Equals("eur"))
                return DestinationCurrency.Eur;

            if (value.Equals("mxn"))
                return DestinationCurrency.Mxn;

            if (value.Equals("usdc"))
                return DestinationCurrency.Usdc;

            if (value.Equals("eurc"))
                return DestinationCurrency.Eurc;

            if (value.Equals("dai"))
                return DestinationCurrency.Dai;

            if (value.Equals("pyusd"))
                return DestinationCurrency.Pyusd;

            if (value.Equals("usdt"))
                return DestinationCurrency.Usdt;

            throw new NotImplementedException($"Could not convert value to type DestinationCurrency: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="DestinationCurrency"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DestinationCurrency? FromStringOrDefault(string value)
        {
            if (value.Equals("usd"))
                return DestinationCurrency.Usd;

            if (value.Equals("eur"))
                return DestinationCurrency.Eur;

            if (value.Equals("mxn"))
                return DestinationCurrency.Mxn;

            if (value.Equals("usdc"))
                return DestinationCurrency.Usdc;

            if (value.Equals("eurc"))
                return DestinationCurrency.Eurc;

            if (value.Equals("dai"))
                return DestinationCurrency.Dai;

            if (value.Equals("pyusd"))
                return DestinationCurrency.Pyusd;

            if (value.Equals("usdt"))
                return DestinationCurrency.Usdt;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DestinationCurrency"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(DestinationCurrency value)
        {
            if (value == DestinationCurrency.Usd)
                return "usd";

            if (value == DestinationCurrency.Eur)
                return "eur";

            if (value == DestinationCurrency.Mxn)
                return "mxn";

            if (value == DestinationCurrency.Usdc)
                return "usdc";

            if (value == DestinationCurrency.Eurc)
                return "eurc";

            if (value == DestinationCurrency.Dai)
                return "dai";

            if (value == DestinationCurrency.Pyusd)
                return "pyusd";

            if (value == DestinationCurrency.Usdt)
                return "usdt";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DestinationCurrency"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class DestinationCurrencyJsonConverter : JsonConverter<DestinationCurrency>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DestinationCurrency Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            DestinationCurrency? result = rawValue == null
                ? null
                : DestinationCurrencyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DestinationCurrency to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="destinationCurrency"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DestinationCurrency destinationCurrency, JsonSerializerOptions options)
        {
            writer.WriteStringValue(DestinationCurrencyValueConverter.ToJsonValue(destinationCurrency).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DestinationCurrency"/>
    /// </summary>
    public class DestinationCurrencyNullableJsonConverter : JsonConverter<DestinationCurrency?>
    {
        /// <summary>
        /// Returns a DestinationCurrency from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DestinationCurrency? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            DestinationCurrency? result = rawValue == null
                ? null
                : DestinationCurrencyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DestinationCurrency to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="destinationCurrency"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DestinationCurrency? destinationCurrency, JsonSerializerOptions options)
        {
            writer.WriteStringValue(destinationCurrency.HasValue ? DestinationCurrencyValueConverter.ToJsonValue(destinationCurrency.Value).ToString() : "null");
        }
    }
}
