// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// The fiat currency to convert FROM. Must match the currency of the source payment rail.
    /// </summary>
    /// <value>The fiat currency to convert FROM. Must match the currency of the source payment rail.</value>
    public enum FiatCurrency
    {
        /// <summary>
        /// Enum Usd for value: usd
        /// </summary>
        Usd = 1,

        /// <summary>
        /// Enum Eur for value: eur
        /// </summary>
        Eur = 2,

        /// <summary>
        /// Enum Mxn for value: mxn
        /// </summary>
        Mxn = 3
    }

    /// <summary>
    /// Converts <see cref="FiatCurrency"/> to and from the JSON value
    /// </summary>
    public static class FiatCurrencyValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="FiatCurrency"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FiatCurrency FromString(string value)
        {
            if (value.Equals("usd"))
                return FiatCurrency.Usd;

            if (value.Equals("eur"))
                return FiatCurrency.Eur;

            if (value.Equals("mxn"))
                return FiatCurrency.Mxn;

            throw new NotImplementedException($"Could not convert value to type FiatCurrency: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="FiatCurrency"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FiatCurrency? FromStringOrDefault(string value)
        {
            if (value.Equals("usd"))
                return FiatCurrency.Usd;

            if (value.Equals("eur"))
                return FiatCurrency.Eur;

            if (value.Equals("mxn"))
                return FiatCurrency.Mxn;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FiatCurrency"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(FiatCurrency value)
        {
            if (value == FiatCurrency.Usd)
                return "usd";

            if (value == FiatCurrency.Eur)
                return "eur";

            if (value == FiatCurrency.Mxn)
                return "mxn";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FiatCurrency"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class FiatCurrencyJsonConverter : JsonConverter<FiatCurrency>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FiatCurrency Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            FiatCurrency? result = rawValue == null
                ? null
                : FiatCurrencyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FiatCurrency to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fiatCurrency"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FiatCurrency fiatCurrency, JsonSerializerOptions options)
        {
            writer.WriteStringValue(FiatCurrencyValueConverter.ToJsonValue(fiatCurrency).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FiatCurrency"/>
    /// </summary>
    public class FiatCurrencyNullableJsonConverter : JsonConverter<FiatCurrency?>
    {
        /// <summary>
        /// Returns a FiatCurrency from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FiatCurrency? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            FiatCurrency? result = rawValue == null
                ? null
                : FiatCurrencyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FiatCurrency to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fiatCurrency"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FiatCurrency? fiatCurrency, JsonSerializerOptions options)
        {
            writer.WriteStringValue(fiatCurrency.HasValue ? FiatCurrencyValueConverter.ToJsonValue(fiatCurrency.Value).ToString() : "null");
        }
    }
}
