// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// HealthResponseDto
    /// </summary>
    public partial class HealthResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthResponseDto" /> class.
        /// </summary>
        /// <param name="status">Overall health status of the service. Returns \&quot;ok\&quot; when healthy, \&quot;error\&quot; when issues detected.</param>
        /// <param name="timestamp">ISO 8601 timestamp when the health check was performed.</param>
        /// <param name="varVersion">Current version of the API service. Useful for debugging and compatibility checks.</param>
        /// <param name="database">Database connectivity status. Shows \&quot;connected\&quot; when database is accessible, \&quot;error\&quot; when connection fails.</param>
        /// <param name="message">Human-readable message describing the current health status and any issues.</param>
        /// <param name="authenticated">Indicates whether the request was properly authenticated. Always true for this endpoint since authentication is required.</param>
        [JsonConstructor]
        public HealthResponseDto(StatusEnum status, DateTime timestamp, string varVersion, DatabaseEnum database, string message, bool authenticated)
        {
            Status = status;
            Timestamp = timestamp;
            VarVersion = varVersion;
            Database = database;
            Message = message;
            Authenticated = authenticated;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Overall health status of the service. Returns \&quot;ok\&quot; when healthy, \&quot;error\&quot; when issues detected.
        /// </summary>
        /// <value>Overall health status of the service. Returns \&quot;ok\&quot; when healthy, \&quot;error\&quot; when issues detected.</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Ok for value: ok
            /// </summary>
            Ok = 1,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            if (value.Equals("error"))
                return StatusEnum.Error;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ok"))
                return StatusEnum.Ok;

            if (value.Equals("error"))
                return StatusEnum.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Ok)
                return "ok";

            if (value == StatusEnum.Error)
                return "error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Overall health status of the service. Returns \&quot;ok\&quot; when healthy, \&quot;error\&quot; when issues detected.
        /// </summary>
        /// <value>Overall health status of the service. Returns \&quot;ok\&quot; when healthy, \&quot;error\&quot; when issues detected.</value>
        /* <example>ok</example> */
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Database connectivity status. Shows \&quot;connected\&quot; when database is accessible, \&quot;error\&quot; when connection fails.
        /// </summary>
        /// <value>Database connectivity status. Shows \&quot;connected\&quot; when database is accessible, \&quot;error\&quot; when connection fails.</value>
        public enum DatabaseEnum
        {
            /// <summary>
            /// Enum Connected for value: connected
            /// </summary>
            Connected = 1,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 2
        }

        /// <summary>
        /// Returns a <see cref="DatabaseEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static DatabaseEnum DatabaseEnumFromString(string value)
        {
            if (value.Equals("connected"))
                return DatabaseEnum.Connected;

            if (value.Equals("error"))
                return DatabaseEnum.Error;

            throw new NotImplementedException($"Could not convert value to type DatabaseEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="DatabaseEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DatabaseEnum? DatabaseEnumFromStringOrDefault(string value)
        {
            if (value.Equals("connected"))
                return DatabaseEnum.Connected;

            if (value.Equals("error"))
                return DatabaseEnum.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DatabaseEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string DatabaseEnumToJsonValue(DatabaseEnum value)
        {
            if (value == DatabaseEnum.Connected)
                return "connected";

            if (value == DatabaseEnum.Error)
                return "error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Database connectivity status. Shows \&quot;connected\&quot; when database is accessible, \&quot;error\&quot; when connection fails.
        /// </summary>
        /// <value>Database connectivity status. Shows \&quot;connected\&quot; when database is accessible, \&quot;error\&quot; when connection fails.</value>
        /* <example>connected</example> */
        [JsonPropertyName("database")]
        public DatabaseEnum Database { get; set; }

        /// <summary>
        /// ISO 8601 timestamp when the health check was performed.
        /// </summary>
        /// <value>ISO 8601 timestamp when the health check was performed.</value>
        /* <example>2023-07-01T12:00Z</example> */
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Current version of the API service. Useful for debugging and compatibility checks.
        /// </summary>
        /// <value>Current version of the API service. Useful for debugging and compatibility checks.</value>
        /* <example>1.0.0</example> */
        [JsonPropertyName("version")]
        public string VarVersion { get; set; }

        /// <summary>
        /// Human-readable message describing the current health status and any issues.
        /// </summary>
        /// <value>Human-readable message describing the current health status and any issues.</value>
        /* <example>Service is up and running</example> */
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Indicates whether the request was properly authenticated. Always true for this endpoint since authentication is required.
        /// </summary>
        /// <value>Indicates whether the request was properly authenticated. Always true for this endpoint since authentication is required.</value>
        /* <example>true</example> */
        [JsonPropertyName("authenticated")]
        public bool Authenticated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthResponseDto {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Authenticated: ").Append(Authenticated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HealthResponseDto" />
    /// </summary>
    public class HealthResponseDtoJsonConverter : JsonConverter<HealthResponseDto>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="HealthResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HealthResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<HealthResponseDto.StatusEnum?> status = default;
            Option<DateTime?> timestamp = default;
            Option<string> varVersion = default;
            Option<HealthResponseDto.DatabaseEnum?> database = default;
            Option<string> message = default;
            Option<bool?> authenticated = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<HealthResponseDto.StatusEnum?>(HealthResponseDto.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "version":
                            varVersion = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "database":
                            string databaseRawValue = utf8JsonReader.GetString();
                            if (databaseRawValue != null)
                                database = new Option<HealthResponseDto.DatabaseEnum?>(HealthResponseDto.DatabaseEnumFromStringOrDefault(databaseRawValue));
                            break;
                        case "message":
                            message = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "authenticated":
                            authenticated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(status));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(timestamp));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(varVersion));

            if (!database.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(database));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(message));

            if (!authenticated.IsSet)
                throw new ArgumentException("Property is required for class HealthResponseDto.", nameof(authenticated));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class HealthResponseDto.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class HealthResponseDto.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class HealthResponseDto.");

            if (database.IsSet && database.Value == null)
                throw new ArgumentNullException(nameof(database), "Property is not nullable for class HealthResponseDto.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class HealthResponseDto.");

            if (authenticated.IsSet && authenticated.Value == null)
                throw new ArgumentNullException(nameof(authenticated), "Property is not nullable for class HealthResponseDto.");

            return new HealthResponseDto(status.Value.Value, timestamp.Value.Value, varVersion.Value, database.Value.Value, message.Value, authenticated.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="HealthResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HealthResponseDto healthResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, healthResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HealthResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HealthResponseDto healthResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (healthResponseDto.VarVersion == null)
                throw new ArgumentNullException(nameof(healthResponseDto.VarVersion), "Property is required for class HealthResponseDto.");

            if (healthResponseDto.Message == null)
                throw new ArgumentNullException(nameof(healthResponseDto.Message), "Property is required for class HealthResponseDto.");

            var statusRawValue = HealthResponseDto.StatusEnumToJsonValue(healthResponseDto.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("timestamp", healthResponseDto.Timestamp.ToString(TimestampFormat));

            writer.WriteString("version", healthResponseDto.VarVersion);

            var databaseRawValue = HealthResponseDto.DatabaseEnumToJsonValue(healthResponseDto.Database);
            writer.WriteString("database", databaseRawValue);
            writer.WriteString("message", healthResponseDto.Message);

            writer.WriteBoolean("authenticated", healthResponseDto.Authenticated);
        }
    }
}
