// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// InvoiceProductDto
    /// </summary>
    public partial class InvoiceProductDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceProductDto" /> class.
        /// </summary>
        /// <param name="productId">Product ID</param>
        /// <param name="quantity">Quantity of the product</param>
        [JsonConstructor]
        public InvoiceProductDto(string productId, decimal quantity)
        {
            ProductId = productId;
            Quantity = quantity;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Product ID
        /// </summary>
        /// <value>Product ID</value>
        [JsonPropertyName("product_id")]
        public string ProductId { get; set; }

        /// <summary>
        /// Quantity of the product
        /// </summary>
        /// <value>Quantity of the product</value>
        [JsonPropertyName("quantity")]
        public decimal Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InvoiceProductDto {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InvoiceProductDto" />
    /// </summary>
    public class InvoiceProductDtoJsonConverter : JsonConverter<InvoiceProductDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="InvoiceProductDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InvoiceProductDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> productId = default;
            Option<decimal?> quantity = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "product_id":
                            productId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "quantity":
                            quantity = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!productId.IsSet)
                throw new ArgumentException("Property is required for class InvoiceProductDto.", nameof(productId));

            if (!quantity.IsSet)
                throw new ArgumentException("Property is required for class InvoiceProductDto.", nameof(quantity));

            if (productId.IsSet && productId.Value == null)
                throw new ArgumentNullException(nameof(productId), "Property is not nullable for class InvoiceProductDto.");

            if (quantity.IsSet && quantity.Value == null)
                throw new ArgumentNullException(nameof(quantity), "Property is not nullable for class InvoiceProductDto.");

            return new InvoiceProductDto(productId.Value, quantity.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="InvoiceProductDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="invoiceProductDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InvoiceProductDto invoiceProductDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, invoiceProductDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InvoiceProductDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="invoiceProductDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InvoiceProductDto invoiceProductDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (invoiceProductDto.ProductId == null)
                throw new ArgumentNullException(nameof(invoiceProductDto.ProductId), "Property is required for class InvoiceProductDto.");

            writer.WriteString("product_id", invoiceProductDto.ProductId);

            writer.WriteNumber("quantity", invoiceProductDto.Quantity);
        }
    }
}
