// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// PaymentRequestDto
    /// </summary>
    public partial class PaymentRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentRequestDto" /> class.
        /// </summary>
        /// <param name="amount">The amount to charge</param>
        /// <param name="currency">The currency code</param>
        /// <param name="description">Description of the payment</param>
        /// <param name="customerId">Customer reference ID</param>
        [JsonConstructor]
        public PaymentRequestDto(decimal amount, string currency, string description, Option<string> customerId = default)
        {
            Amount = amount;
            Currency = currency;
            Description = description;
            CustomerIdOption = customerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The amount to charge
        /// </summary>
        /// <value>The amount to charge</value>
        /* <example>100.5</example> */
        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// The currency code
        /// </summary>
        /// <value>The currency code</value>
        /* <example>USD</example> */
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Description of the payment
        /// </summary>
        /// <value>Description of the payment</value>
        /* <example>Test payment for API</example> */
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CustomerIdOption { get; private set; }

        /// <summary>
        /// Customer reference ID
        /// </summary>
        /// <value>Customer reference ID</value>
        /* <example>cus_12345</example> */
        [JsonPropertyName("customerId")]
        public string CustomerId { get { return this.CustomerIdOption; } set { this.CustomerIdOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentRequestDto {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentRequestDto" />
    /// </summary>
    public class PaymentRequestDtoJsonConverter : JsonConverter<PaymentRequestDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="PaymentRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> amount = default;
            Option<string> currency = default;
            Option<string> description = default;
            Option<string> customerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "currency":
                            currency = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customerId":
                            customerId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class PaymentRequestDto.", nameof(amount));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class PaymentRequestDto.", nameof(currency));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class PaymentRequestDto.", nameof(description));

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class PaymentRequestDto.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class PaymentRequestDto.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class PaymentRequestDto.");

            if (customerId.IsSet && customerId.Value == null)
                throw new ArgumentNullException(nameof(customerId), "Property is not nullable for class PaymentRequestDto.");

            return new PaymentRequestDto(amount.Value.Value, currency.Value, description.Value, customerId);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentRequestDto paymentRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentRequestDto paymentRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentRequestDto.Currency == null)
                throw new ArgumentNullException(nameof(paymentRequestDto.Currency), "Property is required for class PaymentRequestDto.");

            if (paymentRequestDto.Description == null)
                throw new ArgumentNullException(nameof(paymentRequestDto.Description), "Property is required for class PaymentRequestDto.");

            if (paymentRequestDto.CustomerIdOption.IsSet && paymentRequestDto.CustomerId == null)
                throw new ArgumentNullException(nameof(paymentRequestDto.CustomerId), "Property is required for class PaymentRequestDto.");

            writer.WriteNumber("amount", paymentRequestDto.Amount);

            writer.WriteString("currency", paymentRequestDto.Currency);

            writer.WriteString("description", paymentRequestDto.Description);

            if (paymentRequestDto.CustomerIdOption.IsSet)
                writer.WriteString("customerId", paymentRequestDto.CustomerId);
        }
    }
}
