// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// RefundResponseDto
    /// </summary>
    public partial class RefundResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundResponseDto" /> class.
        /// </summary>
        /// <param name="id">Refund ID</param>
        /// <param name="paymentId">Original payment ID</param>
        /// <param name="amount">The amount refunded</param>
        /// <param name="status">Refund status</param>
        /// <param name="timestamp">Timestamp of the refund</param>
        [JsonConstructor]
        public RefundResponseDto(string id, string paymentId, decimal amount, string status, string timestamp)
        {
            Id = id;
            PaymentId = paymentId;
            Amount = amount;
            Status = status;
            Timestamp = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Refund ID
        /// </summary>
        /// <value>Refund ID</value>
        /* <example>ref_12345abcdef</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Original payment ID
        /// </summary>
        /// <value>Original payment ID</value>
        /* <example>pay_12345abcdef</example> */
        [JsonPropertyName("paymentId")]
        public string PaymentId { get; set; }

        /// <summary>
        /// The amount refunded
        /// </summary>
        /// <value>The amount refunded</value>
        /* <example>100.5</example> */
        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Refund status
        /// </summary>
        /// <value>Refund status</value>
        /* <example>succeeded</example> */
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Timestamp of the refund
        /// </summary>
        /// <value>Timestamp of the refund</value>
        /* <example>2023-07-01T12:00:00.000Z</example> */
        [JsonPropertyName("timestamp")]
        public string Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundResponseDto" />
    /// </summary>
    public class RefundResponseDtoJsonConverter : JsonConverter<RefundResponseDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="RefundResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RefundResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> id = default;
            Option<string> paymentId = default;
            Option<decimal?> amount = default;
            Option<string> status = default;
            Option<string> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "paymentId":
                            paymentId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            status = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "timestamp":
                            timestamp = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class RefundResponseDto.", nameof(id));

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class RefundResponseDto.", nameof(paymentId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class RefundResponseDto.", nameof(amount));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class RefundResponseDto.", nameof(status));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class RefundResponseDto.", nameof(timestamp));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class RefundResponseDto.");

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class RefundResponseDto.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class RefundResponseDto.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class RefundResponseDto.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class RefundResponseDto.");

            return new RefundResponseDto(id.Value, paymentId.Value, amount.Value.Value, status.Value, timestamp.Value);
        }

        /// <summary>
        /// Serializes a <see cref="RefundResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RefundResponseDto refundResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, refundResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RefundResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RefundResponseDto refundResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (refundResponseDto.Id == null)
                throw new ArgumentNullException(nameof(refundResponseDto.Id), "Property is required for class RefundResponseDto.");

            if (refundResponseDto.PaymentId == null)
                throw new ArgumentNullException(nameof(refundResponseDto.PaymentId), "Property is required for class RefundResponseDto.");

            if (refundResponseDto.Status == null)
                throw new ArgumentNullException(nameof(refundResponseDto.Status), "Property is required for class RefundResponseDto.");

            if (refundResponseDto.Timestamp == null)
                throw new ArgumentNullException(nameof(refundResponseDto.Timestamp), "Property is required for class RefundResponseDto.");

            writer.WriteString("id", refundResponseDto.Id);

            writer.WriteString("paymentId", refundResponseDto.PaymentId);

            writer.WriteNumber("amount", refundResponseDto.Amount);

            writer.WriteString("status", refundResponseDto.Status);

            writer.WriteString("timestamp", refundResponseDto.Timestamp);
        }
    }
}
