// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// UpdateCustomerDto
    /// </summary>
    public partial class UpdateCustomerDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCustomerDto" /> class.
        /// </summary>
        /// <param name="firstName">Customer&#39;s first name. Used for personalization and legal documentation.</param>
        /// <param name="lastName">Customer&#39;s last name. Used for personalization and legal documentation.</param>
        /// <param name="email">Customer&#39;s email address. Used for notifications, receipts, and account management. Must be a valid email format.</param>
        /// <param name="phoneNumber">Customer&#39;s phone number. Used for SMS notifications and verification. Include country code for international numbers.</param>
        /// <param name="customerType">Type of customer account. Determines available features and compliance requirements.</param>
        /// <param name="status">Current status of the customer account. Controls access to services and features.</param>
        [JsonConstructor]
        public UpdateCustomerDto(Option<string> firstName = default, Option<string> lastName = default, Option<string> email = default, Option<string> phoneNumber = default, Option<CustomerType?> customerType = default, Option<CustomerStatus?> status = default)
        {
            FirstNameOption = firstName;
            LastNameOption = lastName;
            EmailOption = email;
            PhoneNumberOption = phoneNumber;
            CustomerTypeOption = customerType;
            StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CustomerType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CustomerType?> CustomerTypeOption { get; private set; }

        /// <summary>
        /// Type of customer account. Determines available features and compliance requirements.
        /// </summary>
        /// <value>Type of customer account. Determines available features and compliance requirements.</value>
        [JsonPropertyName("customer_type")]
        public CustomerType? CustomerType { get { return this.CustomerTypeOption; } set { this.CustomerTypeOption = new Option<CustomerType?>(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CustomerStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Current status of the customer account. Controls access to services and features.
        /// </summary>
        /// <value>Current status of the customer account. Controls access to services and features.</value>
        [JsonPropertyName("status")]
        public CustomerStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new Option<CustomerStatus?>(value); } }

        /// <summary>
        /// Used to track the state of FirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> FirstNameOption { get; private set; }

        /// <summary>
        /// Customer&#39;s first name. Used for personalization and legal documentation.
        /// </summary>
        /// <value>Customer&#39;s first name. Used for personalization and legal documentation.</value>
        /* <example>John</example> */
        [JsonPropertyName("first_name")]
        public string FirstName { get { return this.FirstNameOption; } set { this.FirstNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of LastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> LastNameOption { get; private set; }

        /// <summary>
        /// Customer&#39;s last name. Used for personalization and legal documentation.
        /// </summary>
        /// <value>Customer&#39;s last name. Used for personalization and legal documentation.</value>
        /* <example>Doe</example> */
        [JsonPropertyName("last_name")]
        public string LastName { get { return this.LastNameOption; } set { this.LastNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> EmailOption { get; private set; }

        /// <summary>
        /// Customer&#39;s email address. Used for notifications, receipts, and account management. Must be a valid email format.
        /// </summary>
        /// <value>Customer&#39;s email address. Used for notifications, receipts, and account management. Must be a valid email format.</value>
        /* <example>john.doe@example.com</example> */
        [JsonPropertyName("email")]
        public string Email { get { return this.EmailOption; } set { this.EmailOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PhoneNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhoneNumberOption { get; private set; }

        /// <summary>
        /// Customer&#39;s phone number. Used for SMS notifications and verification. Include country code for international numbers.
        /// </summary>
        /// <value>Customer&#39;s phone number. Used for SMS notifications and verification. Include country code for international numbers.</value>
        /* <example>+1-555-123-4567</example> */
        [JsonPropertyName("phone_number")]
        public string PhoneNumber { get { return this.PhoneNumberOption; } set { this.PhoneNumberOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCustomerDto {\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  CustomerType: ").Append(CustomerType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FirstName (string) maxLength
            if (this.FirstName != null && this.FirstName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for FirstName, length must be less than 100.", new [] { "FirstName" });
            }

            // FirstName (string) minLength
            if (this.FirstName != null && this.FirstName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for FirstName, length must be greater than 1.", new [] { "FirstName" });
            }

            // LastName (string) maxLength
            if (this.LastName != null && this.LastName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for LastName, length must be less than 100.", new [] { "LastName" });
            }

            // LastName (string) minLength
            if (this.LastName != null && this.LastName.Length < 1)
            {
                yield return new ValidationResult("Invalid value for LastName, length must be greater than 1.", new [] { "LastName" });
            }

            if (this.PhoneNumberOption.Value != null) {
                // PhoneNumber (string) pattern
                Regex regexPhoneNumber = new Regex(@"^[+]?[1-9]\d{1,14}$", RegexOptions.CultureInvariant);

                if (this.PhoneNumberOption.Value != null &&!regexPhoneNumber.Match(this.PhoneNumberOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, must match a pattern of " + regexPhoneNumber, new [] { "PhoneNumber" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateCustomerDto" />
    /// </summary>
    public class UpdateCustomerDtoJsonConverter : JsonConverter<UpdateCustomerDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateCustomerDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateCustomerDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> firstName = default;
            Option<string> lastName = default;
            Option<string> email = default;
            Option<string> phoneNumber = default;
            Option<CustomerType?> customerType = default;
            Option<CustomerStatus?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "first_name":
                            firstName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "last_name":
                            lastName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phone_number":
                            phoneNumber = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "customer_type":
                            string customerTypeRawValue = utf8JsonReader.GetString();
                            if (customerTypeRawValue != null)
                                customerType = new Option<CustomerType?>(CustomerTypeValueConverter.FromStringOrDefault(customerTypeRawValue));
                            break;
                        case "status":
                            string statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<CustomerStatus?>(CustomerStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (firstName.IsSet && firstName.Value == null)
                throw new ArgumentNullException(nameof(firstName), "Property is not nullable for class UpdateCustomerDto.");

            if (lastName.IsSet && lastName.Value == null)
                throw new ArgumentNullException(nameof(lastName), "Property is not nullable for class UpdateCustomerDto.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class UpdateCustomerDto.");

            if (phoneNumber.IsSet && phoneNumber.Value == null)
                throw new ArgumentNullException(nameof(phoneNumber), "Property is not nullable for class UpdateCustomerDto.");

            if (customerType.IsSet && customerType.Value == null)
                throw new ArgumentNullException(nameof(customerType), "Property is not nullable for class UpdateCustomerDto.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class UpdateCustomerDto.");

            return new UpdateCustomerDto(firstName, lastName, email, phoneNumber, customerType, status);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateCustomerDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCustomerDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateCustomerDto updateCustomerDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateCustomerDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateCustomerDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCustomerDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateCustomerDto updateCustomerDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateCustomerDto.FirstNameOption.IsSet && updateCustomerDto.FirstName == null)
                throw new ArgumentNullException(nameof(updateCustomerDto.FirstName), "Property is required for class UpdateCustomerDto.");

            if (updateCustomerDto.LastNameOption.IsSet && updateCustomerDto.LastName == null)
                throw new ArgumentNullException(nameof(updateCustomerDto.LastName), "Property is required for class UpdateCustomerDto.");

            if (updateCustomerDto.EmailOption.IsSet && updateCustomerDto.Email == null)
                throw new ArgumentNullException(nameof(updateCustomerDto.Email), "Property is required for class UpdateCustomerDto.");

            if (updateCustomerDto.PhoneNumberOption.IsSet && updateCustomerDto.PhoneNumber == null)
                throw new ArgumentNullException(nameof(updateCustomerDto.PhoneNumber), "Property is required for class UpdateCustomerDto.");

            if (updateCustomerDto.FirstNameOption.IsSet)
                writer.WriteString("first_name", updateCustomerDto.FirstName);

            if (updateCustomerDto.LastNameOption.IsSet)
                writer.WriteString("last_name", updateCustomerDto.LastName);

            if (updateCustomerDto.EmailOption.IsSet)
                writer.WriteString("email", updateCustomerDto.Email);

            if (updateCustomerDto.PhoneNumberOption.IsSet)
                writer.WriteString("phone_number", updateCustomerDto.PhoneNumber);

            if (updateCustomerDto.CustomerTypeOption.IsSet)
            {
                var customerTypeRawValue = CustomerTypeValueConverter.ToJsonValue(updateCustomerDto.CustomerType.Value);
                writer.WriteString("customer_type", customerTypeRawValue);
            }
            if (updateCustomerDto.StatusOption.IsSet)
            {
                var statusRawValue = CustomerStatusValueConverter.ToJsonValue(updateCustomerDto.Status.Value);
                writer.WriteString("status", statusRawValue);
            }
        }
    }
}
