// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// UpdateWebhookDto
    /// </summary>
    public partial class UpdateWebhookDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateWebhookDto" /> class.
        /// </summary>
        /// <param name="name">Name of the webhook for identification purposes</param>
        /// <param name="url">URL where webhook events will be sent</param>
        /// <param name="isActive">Whether the webhook is active and will receive events (default to true)</param>
        /// <param name="signingSecret">Secret key used to sign webhook payloads for verification</param>
        /// <param name="encrypted">Whether webhook payloads should be encrypted (default to false)</param>
        [JsonConstructor]
        public UpdateWebhookDto(Option<string> name = default, Option<string> url = default, Option<bool?> isActive = default, Option<string> signingSecret = default, Option<bool?> encrypted = default)
        {
            NameOption = name;
            UrlOption = url;
            IsActiveOption = isActive;
            SigningSecretOption = signingSecret;
            EncryptedOption = encrypted;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Name of the webhook for identification purposes
        /// </summary>
        /// <value>Name of the webhook for identification purposes</value>
        /* <example>Payment Notifications</example> */
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UrlOption { get; private set; }

        /// <summary>
        /// URL where webhook events will be sent
        /// </summary>
        /// <value>URL where webhook events will be sent</value>
        /* <example>https://api.example.com/webhooks/payments</example> */
        [JsonPropertyName("url")]
        public string Url { get { return this.UrlOption; } set { this.UrlOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Whether the webhook is active and will receive events
        /// </summary>
        /// <value>Whether the webhook is active and will receive events</value>
        /* <example>true</example> */
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption; } set { this.IsActiveOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of SigningSecret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> SigningSecretOption { get; private set; }

        /// <summary>
        /// Secret key used to sign webhook payloads for verification
        /// </summary>
        /// <value>Secret key used to sign webhook payloads for verification</value>
        /* <example>whsec_123456789</example> */
        [JsonPropertyName("signing_secret")]
        public string SigningSecret { get { return this.SigningSecretOption; } set { this.SigningSecretOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Encrypted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EncryptedOption { get; private set; }

        /// <summary>
        /// Whether webhook payloads should be encrypted
        /// </summary>
        /// <value>Whether webhook payloads should be encrypted</value>
        /* <example>false</example> */
        [JsonPropertyName("encrypted")]
        public bool? Encrypted { get { return this.EncryptedOption; } set { this.EncryptedOption = new Option<bool?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateWebhookDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  SigningSecret: ").Append(SigningSecret).Append("\n");
            sb.Append("  Encrypted: ").Append(Encrypted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 3.", new [] { "Name" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateWebhookDto" />
    /// </summary>
    public class UpdateWebhookDtoJsonConverter : JsonConverter<UpdateWebhookDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateWebhookDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateWebhookDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> url = default;
            Option<bool?> isActive = default;
            Option<string> signingSecret = default;
            Option<bool?> encrypted = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "signing_secret":
                            signingSecret = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "encrypted":
                            encrypted = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateWebhookDto.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class UpdateWebhookDto.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class UpdateWebhookDto.");

            if (signingSecret.IsSet && signingSecret.Value == null)
                throw new ArgumentNullException(nameof(signingSecret), "Property is not nullable for class UpdateWebhookDto.");

            if (encrypted.IsSet && encrypted.Value == null)
                throw new ArgumentNullException(nameof(encrypted), "Property is not nullable for class UpdateWebhookDto.");

            return new UpdateWebhookDto(name, url, isActive, signingSecret, encrypted);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateWebhookDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateWebhookDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateWebhookDto updateWebhookDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateWebhookDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateWebhookDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateWebhookDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateWebhookDto updateWebhookDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateWebhookDto.NameOption.IsSet && updateWebhookDto.Name == null)
                throw new ArgumentNullException(nameof(updateWebhookDto.Name), "Property is required for class UpdateWebhookDto.");

            if (updateWebhookDto.UrlOption.IsSet && updateWebhookDto.Url == null)
                throw new ArgumentNullException(nameof(updateWebhookDto.Url), "Property is required for class UpdateWebhookDto.");

            if (updateWebhookDto.SigningSecretOption.IsSet && updateWebhookDto.SigningSecret == null)
                throw new ArgumentNullException(nameof(updateWebhookDto.SigningSecret), "Property is required for class UpdateWebhookDto.");

            if (updateWebhookDto.NameOption.IsSet)
                writer.WriteString("name", updateWebhookDto.Name);

            if (updateWebhookDto.UrlOption.IsSet)
                writer.WriteString("url", updateWebhookDto.Url);

            if (updateWebhookDto.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", updateWebhookDto.IsActiveOption.Value.Value);

            if (updateWebhookDto.SigningSecretOption.IsSet)
                writer.WriteString("signing_secret", updateWebhookDto.SigningSecret);

            if (updateWebhookDto.EncryptedOption.IsSet)
                writer.WriteBoolean("encrypted", updateWebhookDto.EncryptedOption.Value.Value);
        }
    }
}
