// <auto-generated>
/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Devdraft.Client;

namespace Devdraft.Model
{
    /// <summary>
    /// UpdateTaxDto
    /// </summary>
    public partial class UpdateTaxDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateTaxDto" /> class.
        /// </summary>
        /// <param name="name">Tax name for identification and display purposes</param>
        /// <param name="description">Detailed description of what this tax covers</param>
        /// <param name="percentage">Tax rate as a percentage (0-100)</param>
        /// <param name="active">Whether this tax is currently active and can be applied</param>
        /// <param name="appIds">Array of app IDs where this tax should be available</param>
        [JsonConstructor]
        public UpdateTaxDto(Option<string> name = default, Option<string> description = default, Option<decimal?> percentage = default, Option<bool?> active = default, Option<List<Guid>> appIds = default)
        {
            NameOption = name;
            DescriptionOption = description;
            PercentageOption = percentage;
            ActiveOption = active;
            AppIdsOption = appIds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Tax name for identification and display purposes
        /// </summary>
        /// <value>Tax name for identification and display purposes</value>
        /* <example>Updated Sales Tax</example> */
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DescriptionOption { get; private set; }

        /// <summary>
        /// Detailed description of what this tax covers
        /// </summary>
        /// <value>Detailed description of what this tax covers</value>
        /* <example>Updated description for retail sales tax</example> */
        [JsonPropertyName("description")]
        public string Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Percentage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PercentageOption { get; private set; }

        /// <summary>
        /// Tax rate as a percentage (0-100)
        /// </summary>
        /// <value>Tax rate as a percentage (0-100)</value>
        /* <example>9.5</example> */
        [JsonPropertyName("percentage")]
        public decimal? Percentage { get { return this.PercentageOption; } set { this.PercentageOption = new Option<decimal?>(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; private set; }

        /// <summary>
        /// Whether this tax is currently active and can be applied
        /// </summary>
        /// <value>Whether this tax is currently active and can be applied</value>
        /* <example>false</example> */
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } set { this.ActiveOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of AppIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Guid>> AppIdsOption { get; private set; }

        /// <summary>
        /// Array of app IDs where this tax should be available
        /// </summary>
        /// <value>Array of app IDs where this tax should be available</value>
        /* <example>[&quot;app_123e4567-e89b-12d3-a456-426614174000&quot;]</example> */
        [JsonPropertyName("appIds")]
        public List<Guid> AppIds { get { return this.AppIdsOption; } set { this.AppIdsOption = new Option<List<Guid>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateTaxDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Percentage: ").Append(Percentage).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  AppIds: ").Append(AppIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 255.", new [] { "Description" });
            }

            // Percentage (decimal) maximum
            if (this.PercentageOption.IsSet && this.PercentageOption.Value > (decimal)100)
            {
                yield return new ValidationResult("Invalid value for Percentage, must be a value less than or equal to 100.", new [] { "Percentage" });
            }

            // Percentage (decimal) minimum
            if (this.PercentageOption.IsSet && this.PercentageOption.Value < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for Percentage, must be a value greater than or equal to 0.", new [] { "Percentage" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateTaxDto" />
    /// </summary>
    public class UpdateTaxDtoJsonConverter : JsonConverter<UpdateTaxDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateTaxDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateTaxDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> description = default;
            Option<decimal?> percentage = default;
            Option<bool?> active = default;
            Option<List<Guid>> appIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "percentage":
                            percentage = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "active":
                            active = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "appIds":
                            appIds = new Option<List<Guid>>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateTaxDto.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class UpdateTaxDto.");

            if (percentage.IsSet && percentage.Value == null)
                throw new ArgumentNullException(nameof(percentage), "Property is not nullable for class UpdateTaxDto.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class UpdateTaxDto.");

            if (appIds.IsSet && appIds.Value == null)
                throw new ArgumentNullException(nameof(appIds), "Property is not nullable for class UpdateTaxDto.");

            return new UpdateTaxDto(name, description, percentage, active, appIds);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateTaxDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateTaxDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateTaxDto updateTaxDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateTaxDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateTaxDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateTaxDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateTaxDto updateTaxDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateTaxDto.NameOption.IsSet && updateTaxDto.Name == null)
                throw new ArgumentNullException(nameof(updateTaxDto.Name), "Property is required for class UpdateTaxDto.");

            if (updateTaxDto.DescriptionOption.IsSet && updateTaxDto.Description == null)
                throw new ArgumentNullException(nameof(updateTaxDto.Description), "Property is required for class UpdateTaxDto.");

            if (updateTaxDto.AppIdsOption.IsSet && updateTaxDto.AppIds == null)
                throw new ArgumentNullException(nameof(updateTaxDto.AppIds), "Property is required for class UpdateTaxDto.");

            if (updateTaxDto.NameOption.IsSet)
                writer.WriteString("name", updateTaxDto.Name);

            if (updateTaxDto.DescriptionOption.IsSet)
                writer.WriteString("description", updateTaxDto.Description);

            if (updateTaxDto.PercentageOption.IsSet)
                writer.WriteNumber("percentage", updateTaxDto.PercentageOption.Value.Value);

            if (updateTaxDto.ActiveOption.IsSet)
                writer.WriteBoolean("active", updateTaxDto.ActiveOption.Value.Value);

            if (updateTaxDto.AppIdsOption.IsSet)
            {
                writer.WritePropertyName("appIds");
                JsonSerializer.Serialize(writer, updateTaxDto.AppIds, jsonSerializerOptions);
            }
        }
    }
}
