/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Devdraft.Api;
using Devdraft.Model;

namespace Devdraft.Client
{
    /// <summary>
    /// Provides hosting configuration for Devdraft
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new AggregatedBalanceResponseJsonConverter());
            _jsonOptions.Converters.Add(new AllBalancesResponseJsonConverter());
            _jsonOptions.Converters.Add(new BridgeFiatPaymentRailJsonConverter());
            _jsonOptions.Converters.Add(new BridgeFiatPaymentRailNullableJsonConverter());
            _jsonOptions.Converters.Add(new BridgePaymentRailJsonConverter());
            _jsonOptions.Converters.Add(new BridgePaymentRailNullableJsonConverter());
            _jsonOptions.Converters.Add(new CreateBankPaymentIntentDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateCustomerDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateDirectBankTransferDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateDirectWalletTransferDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateExternalBankTransferDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateExternalStablecoinTransferDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateInvoiceDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateLiquidationAddressDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreatePaymentLinkDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateStablePaymentIntentDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateStablecoinConversionDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateTaxDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateWebhookDtoJsonConverter());
            _jsonOptions.Converters.Add(new CustomerStatusJsonConverter());
            _jsonOptions.Converters.Add(new CustomerStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new CustomerTypeJsonConverter());
            _jsonOptions.Converters.Add(new CustomerTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DestinationCurrencyJsonConverter());
            _jsonOptions.Converters.Add(new DestinationCurrencyNullableJsonConverter());
            _jsonOptions.Converters.Add(new ExchangeRateResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new FiatCurrencyJsonConverter());
            _jsonOptions.Converters.Add(new FiatCurrencyNullableJsonConverter());
            _jsonOptions.Converters.Add(new HealthResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new InvoiceProductDtoJsonConverter());
            _jsonOptions.Converters.Add(new LiquidationAddressResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new PaymentLinkProductDtoJsonConverter());
            _jsonOptions.Converters.Add(new PaymentRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new PaymentResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new PublicHealthResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new RefundResponseDtoJsonConverter());
            _jsonOptions.Converters.Add(new StableCoinCurrencyJsonConverter());
            _jsonOptions.Converters.Add(new StableCoinCurrencyNullableJsonConverter());
            _jsonOptions.Converters.Add(new TaxControllerCreate201ResponseJsonConverter());
            _jsonOptions.Converters.Add(new TaxControllerDeleteWithoutId400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new TaxControllerUpdateWithoutId400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCustomerDtoJsonConverter());
            _jsonOptions.Converters.Add(new UpdateTaxDtoJsonConverter());
            _jsonOptions.Converters.Add(new UpdateWebhookDtoJsonConverter());
            _jsonOptions.Converters.Add(new WebhookResponseDtoJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new JsonSerializerOptionsProvider(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<APIHealthApiEvents>();
            _services.AddSingleton<AppBalancesApiEvents>();
            _services.AddSingleton<CustomersApiEvents>();
            _services.AddSingleton<ExchangeRatesApiEvents>();
            _services.AddSingleton<InvoicesApiEvents>();
            _services.AddSingleton<LiquidationAddressesApiEvents>();
            _services.AddSingleton<PaymentIntentsApiEvents>();
            _services.AddSingleton<PaymentLinksApiEvents>();
            _services.AddSingleton<ProductsApiEvents>();
            _services.AddSingleton<TaxesApiEvents>();
            _services.AddSingleton<TestPaymentsApiEvents>();
            _services.AddSingleton<TransfersApiEvents>();
            _services.AddSingleton<WalletsApiEvents>();
            _services.AddSingleton<WebhooksApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient> client = null, Action<IHttpClientBuilder> builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAPIHealthApi, APIHealthApi>(client));
            builders.Add(_services.AddHttpClient<IAppBalancesApi, AppBalancesApi>(client));
            builders.Add(_services.AddHttpClient<ICustomersApi, CustomersApi>(client));
            builders.Add(_services.AddHttpClient<IExchangeRatesApi, ExchangeRatesApi>(client));
            builders.Add(_services.AddHttpClient<IInvoicesApi, InvoicesApi>(client));
            builders.Add(_services.AddHttpClient<ILiquidationAddressesApi, LiquidationAddressesApi>(client));
            builders.Add(_services.AddHttpClient<IPaymentIntentsApi, PaymentIntentsApi>(client));
            builders.Add(_services.AddHttpClient<IPaymentLinksApi, PaymentLinksApi>(client));
            builders.Add(_services.AddHttpClient<IProductsApi, ProductsApi>(client));
            builders.Add(_services.AddHttpClient<ITaxesApi, TaxesApi>(client));
            builders.Add(_services.AddHttpClient<ITestPaymentsApi, TestPaymentsApi>(client));
            builders.Add(_services.AddHttpClient<ITransfersApi, TransfersApi>(client));
            builders.Add(_services.AddHttpClient<IWalletsApi, WalletsApi>(client));
            builders.Add(_services.AddHttpClient<IWebhooksApi, WebhooksApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
