/*
 * Devdraft AI Payment & Business Management API
 *
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Devdraft.Api;
using Devdraft.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Devdraft.Test.Api
{
    /// <summary>
    ///  Class for testing TestPaymentsApi
    /// </summary>
    public sealed class TestPaymentsApiTests : ApiTestsBase
    {
        private readonly ITestPaymentsApi _instance;

        public TestPaymentsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITestPaymentsApi>();
        }

        /// <summary>
        /// Test TestPaymentControllerCreatePaymentV0
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestPaymentControllerCreatePaymentV0AsyncTest()
        {
            Guid idempotencyKey = default;
            PaymentRequestDto paymentRequestDto = default;
            var response = await _instance.TestPaymentControllerCreatePaymentV0Async(idempotencyKey, paymentRequestDto);
            var model = response.Created();
            Assert.IsType<PaymentResponseDto>(model);
        }

        /// <summary>
        /// Test TestPaymentControllerGetPaymentV0
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestPaymentControllerGetPaymentV0AsyncTest()
        {
            string id = default;
            var response = await _instance.TestPaymentControllerGetPaymentV0Async(id);
            var model = response.Ok();
            Assert.IsType<PaymentResponseDto>(model);
        }

        /// <summary>
        /// Test TestPaymentControllerRefundPaymentV0
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TestPaymentControllerRefundPaymentV0AsyncTest()
        {
            string id = default;
            Guid idempotencyKey = default;
            var response = await _instance.TestPaymentControllerRefundPaymentV0Async(id, idempotencyKey);
            var model = response.Ok();
            Assert.IsType<RefundResponseDto>(model);
        }
    }
}
